PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS menu; 
CREATE TABLE menu (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT NOT NULL
);
INSERT INTO menu VALUES(1,'The Frosting of the Tips','Spicy Italian Lipid-Thrusted Octopus Flatbread with Galvanized Sweet Potato Jammers Frothing in a Stroh''s Flavor Puddle');
INSERT INTO menu VALUES(2,'We Need To Talk About Kevin','French Canadian Pimento-Tweaked Corgi Hunk with Steamed Zucchini Nugs Mingling in a Bongwater Au Jus');
INSERT INTO menu VALUES(3,'Turn Down for What','Guy''s Own MSG-Murdered Octopus Patties with Thrice-Baked Broccoli Raab Nugs Slam Dunked in a Surge Au Jus');
INSERT INTO menu VALUES(4,'Guyway to Heaven','Guypocalyptic Gruyere-Drilled Veal Loaf with Mentholated Cauliflower Nugs Stroking Out in a Stroh''s Sauce');
INSERT INTO menu VALUES(5,'BeefTech','42 Fluid Ounces of Pimento-Groped Octopus Roast with Pan Seared Sweet Potato Tidbits Waterboarded in a Zima Aioli');
INSERT INTO menu VALUES(6,'Gleaming the Cube Steak','Laser Julienned Onion-Mauled Pancetta Hunk with Steamed Cauliflower Jobbers Sevendusted in a Surge Donkey Sauce');
INSERT INTO menu VALUES(7,'Just the Tip','Fancy Cut Chipotle-Smattered Black Rhino Shank with Fry-olated Jackfruit Portions Stroking Out in a Spray Butter Sauce');
INSERT INTO menu VALUES(8,'The Bringer of Pain to Your Face','Hot Rods of Pecan-Drilled Beef Cutlets with Steamed Wheat Germ Units Waterboarded in a GoGurt Reduction');
INSERT INTO menu VALUES(9,'Juggaloaf','Jack Daniels Gruyere-Smashed Eel Shank with Fingerbanged Sweet Potato Grapplers Holding Their Own in a Zima Au Jus');
INSERT INTO menu VALUES(10,'Guyway to Heaven','Rock and Roll Gruyere-Smattered Baby Seal Flatbread with Taste-tosterone Marinated Jackfruit Nugs Frothing in a Tampico Bouillabaisse');
INSERT INTO menu VALUES(11,'Benghazi!','Hot Rods of Gruyere-Murdered Duckling Burger with Windswept Sweet Potato Grapplers Coming of Age in a Mountain Dew Code Red Bouillabaisse');
INSERT INTO menu VALUES(12,'That''s What She Said','Pittsburgh''s Finest Cool Ranch-Groped Octopus Roast with Finger-Rolled Snow Pea Tidbits Drowning in a Horseradish Demi-glace');
INSERT INTO menu VALUES(13,'Who Let the Dogs In?','Hot Rods of Clam-Groped Octopus Enchiladas with Galvanized Wheat Germ Jammers Implemented in a White Zin Bearnaise');
INSERT INTO menu VALUES(14,'What I Got','Partytime Lipid-Inserted Manatee Patties with Thrice-Baked Sweet Potato Tidbits Stroking Out in a Tampico Donkey Sauce');
INSERT INTO menu VALUES(15,'The Schneider','Peak Season Acai-Anointed Pork Hunk with Thrice-Baked Walnut Flapjacks Stroking Out in a Watermelon Four Loko Bouillabaisse');
INSERT INTO menu VALUES(16,'Who Let the Dogs In?','Rock and Roll Crunch-Groped Pork Roast with Fry-olated Cauliflower Portions Waterboarded in a Zima Donkey Sauce');
INSERT INTO menu VALUES(17,'Tits L''Amour','Guypocalyptic Havarti-Groped Manatee Burger with Croc-Stomped Wheat Germ Griplets Waterboarded in a Powerade Hollandaise');
INSERT INTO menu VALUES(18,'Guyway to Heaven','Laser Julienned Panko-Hammered Manatee Hunk with Pan Seared Butternut Squash Grapplers Mingling in a Horseradish Hollandaise');
INSERT INTO menu VALUES(19,'Benghazi!','Pittsburgh''s Finest MSG-Creamed Eel Slab with Croc-Stomped Edamame Jammers Curdling in a Horseradish Coulis');
INSERT INTO menu VALUES(20,'The Dealbreaker','Pittsburgh''s Finest Pimento-Mauled Lamb Shank with Steamed Zucchini Flapjacks Waterboarded in a Spray Butter Bearnaise');
INSERT INTO menu VALUES(21,'The Vanderbilt','Hot Rods of Acai-Creamed Beef Tips with Galvanized Wheat Germ Grapplers Crying for Help in a Zima Jacuzzi');
INSERT INTO menu VALUES(22,'BeefTech','Guypocalyptic Panko-Hammered Rattlesnake Flatbread with Galvanized Ravioli Rippers Partially Submerged in a Powerade Sauce');
INSERT INTO menu VALUES(23,'PT Cruised','Guy''s Famous Havarti-Fisted Pork Roast with Purse-Snatched Zucchini Units Stroking Out in a Capri Sun Safari Fruits Bouillabaisse');
INSERT INTO menu VALUES(24,'Two Grills One Cup','Laser Julienned Acai-Groped Rattlesnake Patties with Galvanized Walnut Griplets Hangin'' Ten in a 5-Hour Energy Gravy');
INSERT INTO menu VALUES(25,'Lady in Red','French Canadian Cool Ranch-Thrusted Veal Hunk with Powdered Ravioli Rippers Fornicating in a Horseradish Demi-glace');
INSERT INTO menu VALUES(26,'Tijuana Flavorwave','42 Fluid Ounces of Crunch-Thrashed Lamb Slab with Pan Seared Quinoa Flapjacks Sevendusted in a Stroh''s Au Jus');
INSERT INTO menu VALUES(27,'Benghazi!','Guy''s Famous Garlic-Blasted Octopus Doggers with Steamed Ravioli Grapplers Hangin'' Ten in a Mountain Dew Code Red Aioli');
INSERT INTO menu VALUES(28,'My Giant','French Canadian Gruyere-Thrashed Manatee Hunk with Broasted Quinoa Units Sevendusted in a Stroh''s Holocaust');
INSERT INTO menu VALUES(29,'BeefTech','Peak Season Crunch-Mauled Lamb Flatbread with Powdered Edamame Flapjacks Coming of Age in a Horseradish Sauce');
INSERT INTO menu VALUES(30,'Tits L''Amour','Partytime Lipid-Fisted Octopus Flatbread with Galvanized Butternut Squash Units Waterboarded in a Zima Demi-glace');
INSERT INTO menu VALUES(31,'Tijuana Flavorwave','Guy''s Own Onion-Blasted Black Rhino Patties with Mentholated Wheat Germ Jobbers Floating in an Arizona Iced Tea Sauce');
INSERT INTO menu VALUES(32,'The Ghost Dad','Laser Julienned Chipotle-Groped Pancetta Flatbread with Pan Seared Cauliflower Grapplers Fornicating in a Sunny D Donkey Sauce');
INSERT INTO menu VALUES(33,'Tits L''Amour','Olde Tyme MSG-Smattered Bison Bits with Pan Seared Broccoli Raab Flapjacks Mingling in a Clotted Cream Au Jus');
INSERT INTO menu VALUES(34,'Dr. T and the Women','Pittsburgh''s Finest Chipotle-Inserted Duckling Doggers with Mentholated Wheat Germ Griplets Coming of Age in a Clarified Lard Flavor Puddle');
INSERT INTO menu VALUES(35,'My Giant','Guy''s Famous Cool Ranch-Mauled Baby Seal Loaf with Fingerbanged Sweet Potato Jobbers Fornicating in a Capri Sun Safari Fruits Gravy');
INSERT INTO menu VALUES(36,'The Dealbreaker','Hot Rods of Panko-Tweaked Eel Shank with Finger-Rolled Zucchini Jobbers Crying for Help in a GoGurt Hearse');
INSERT INTO menu VALUES(37,'The Vanderbilt','French Canadian MSG-Creamed Beef Hunk with Taste-tosterone Marinated Asparagus Nugs Crying for Help in a Queso Sauce');
INSERT INTO menu VALUES(38,'Who Let the Dogs In?','All-American Pecan-Hammered Pancetta Loaf with Powdered Asparagus Griplets Crying for Help in a Bongwater Bearnaise');
INSERT INTO menu VALUES(39,'Guyway to Heaven','Partytime Gruyere-Inserted Lamb Bits with Broasted Walnut Portions Marinated in a Queso Flavor Puddle');
INSERT INTO menu VALUES(40,'The Vanderbilt','Rock and Roll Cool Ranch-Fisted Bison Roast with Broasted Wheat Germ Portions Fornicating in a 5-Hour Energy Demi-glace');
INSERT INTO menu VALUES(41,'Just the Tip','Rock and Roll Cool Ranch-Blasted Rattlesnake Burger with Fingerbanged Wheat Germ Jammers Crying for Help in a Mr. Pibb Au Jus');
INSERT INTO menu VALUES(42,'Jingle All the Way','42 Fluid Ounces of MSG-Smattered Baby Seal Hunk with Purse-Snatched Jackfruit Flapjacks Twerking in a GoGurt Jacuzzi');
INSERT INTO menu VALUES(43,'The Vanderbilt','Olde Tyme Onion-Blasted Rattlesnake Bits with Croc-Stomped Wheat Germ Portions Slam Dunked in a Clarified Lard Coulis');
INSERT INTO menu VALUES(44,'Drops of Jupiter','Peak Season Gluten-Thrusted Manatee Flatbread with Croc-Stomped Asparagus Portions Twerking in a Watermelon Four Loko Reduction');
INSERT INTO menu VALUES(45,'The Bringer of Pain to Your Face','Peak Season Chipotle-Drilled Bacon Flatbread with Fry-olated Jackfruit Grapplers Implemented in a Spray Butter Demi-glace');
INSERT INTO menu VALUES(46,'The Frosting of the Tips','Jack Daniels Cheddar-Drilled Eel Cutlets with Powdered Sweet Potato Jammers Stroking Out in a Stroh''s Bearnaise');
INSERT INTO menu VALUES(47,'The Treat Williams','Guy''s Famous Lipid-Inserted Falafel Enchiladas with Powdered Broccoli Raab Griplets Coming of Age in a Tampico Sauce');
INSERT INTO menu VALUES(48,'Drops of Jupiter','Pittsburgh''s Finest Lipid-Creamed Beef Shank with Broasted Cauliflower Flapjacks Sevendusted in a Clarified Lard Sauce');
INSERT INTO menu VALUES(49,'What I Got','Spicy Italian Gruyere-Smattered Duckling Doggers with Triple-Fried Quinoa Rippers Stroking Out in a Tampico Donkey Sauce');
INSERT INTO menu VALUES(50,'That''s What She Said','42 Fluid Ounces of Crunch-Hammered Baby Seal Hunk with Croc-Stomped Walnut Clumps Implemented in a White Zin Donkey Sauce');
INSERT INTO menu VALUES(51,'Snakes on a Plate','Jack Daniels Pecan-Thrashed Black Rhino Burger with Windswept Walnut Grapplers Drowning in a Tampico Reduction');
INSERT INTO menu VALUES(52,'All the Pretty Horses','All-American Onion-Murdered Corgi Patties with Powdered Ravioli Units Partying ''til Dawn in a Horseradish Holocaust');
INSERT INTO menu VALUES(53,'Three Men and a Little Gravy','Fancy Cut Pimento-Groped Black Rhino Slab with Powdered Quinoa Jammers Waterboarded in a Mountain Dew Code Red Demi-glace');
INSERT INTO menu VALUES(54,'The Truth About Cats and Dogs','Laser Julienned Gruyere-Creamed Bacon Roast with Triple-Fried Cauliflower Jobbers Partying ''til Dawn in a Tampico Bouillabaisse');
INSERT INTO menu VALUES(55,'40 oz to Freedom','Fancy Cut Onion-Inserted Bison Doggers with Steamed Snow Pea Flapjacks Slam Dunked in a Zima Reduction');
INSERT INTO menu VALUES(56,'The Frosting of the Tips','Spicy Italian Onion-Smashed Pancetta Tips with Triple-Fried Sweet Potato Tidbits Frothing in a Spray Butter Donkey Sauce');
INSERT INTO menu VALUES(57,'PT Cruised','Uncle Kracker''s Signature Havarti-Groped Eel Roast with Fry-olated Broccoli Raab Rippers Implemented in a Mountain Dew Code Red Aioli');
INSERT INTO menu VALUES(58,'The Frosting of the Tips','Guypocalyptic Pecan-Tweaked Rattlesnake Burger with Vaped Butternut Squash Jammers Hangin'' Ten in an Arizona Iced Tea Demi-glace');
INSERT INTO menu VALUES(59,'The Truth About Cats and Dogs','Jack Daniels Gruyere-Blasted Rattlesnake Loaf with Steamed Broccoli Raab Rippers Marinated in a 5-Hour Energy Au Jus');
INSERT INTO menu VALUES(60,'Dr. T and the Women','Laser Julienned Clam-Blasted Pancetta Loaf with Finger-Rolled Walnut Jobbers Frothing in a Queso Bouillabaisse');
INSERT INTO menu VALUES(61,'BeefTech','Guy''s Own Crunch-Fisted Bacon Doggers with Fire Bruised Asparagus Grapplers Slam Dunked in a Capri Sun Safari Fruits Reduction');
INSERT INTO menu VALUES(62,'Jingle All the Way','Uncle Kracker''s Signature Lipid-Smashed Lamb Tips with Windswept Asparagus Rippers Partially Submerged in a Mountain Dew Code Red Holocaust');
INSERT INTO menu VALUES(63,'40 oz to Freedom','Laser Julienned MSG-Tweaked Duckling Patties with Steamed Sweet Potato Jammers Partially Submerged in a Sunny D Hollandaise');
INSERT INTO menu VALUES(64,'Lemonparty','Olde Tyme Gluten-Thrusted Beef Roast with Vaped Butternut Squash Nugs Marinated in a Mountain Dew Code Red Au Jus');
INSERT INTO menu VALUES(65,'My Giant','All-American MSG-Fisted Pancetta Flatbread with Triple-Fried Wheat Germ Jobbers Twerking in a Stroh''s Aioli');
INSERT INTO menu VALUES(66,'Shake That Bear','All-American Crunch-Tweaked Duckling Cutlets with Finger-Rolled Jackfruit Rippers Slam Dunked in a Zima Aioli');
INSERT INTO menu VALUES(67,'Who Let the Dogs In?','Guy''s Famous Havarti-Blasted Manatee Doggers with Powdered Asparagus Flapjacks Hangin'' Ten in a Bongwater Demi-glace');
INSERT INTO menu VALUES(68,'What I Got','Fancy Cut MSG-Thrusted Veal Shank with Broasted Zucchini Jobbers Crucified in a White Zin Demi-glace');
INSERT INTO menu VALUES(69,'Madea''s Family Reunion','Laser Julienned Lipid-Thrusted Bacon Patties with Fire Bruised Quinoa Units Sevendusted in a Stroh''s Jacuzzi');
INSERT INTO menu VALUES(70,'Lady in Red','Olde Tyme Cheddar-Smattered Veal Hunk with Powdered Asparagus Clumps Holding Their Own in a Sunny D Flavor Puddle');
INSERT INTO menu VALUES(71,'40 oz to Freedom','Spicy Italian Lipid-Hammered Duckling Flatbread with Fry-olated Ravioli Portions Holding Their Own in a Surge Hollandaise');
INSERT INTO menu VALUES(72,'Two Grills One Cup','Hot Rods of Crunch-Thrusted Falafel Patties with Galvanized Quinoa Portions Sevendusted in a Watermelon Four Loko Coulis');
INSERT INTO menu VALUES(73,'The Vanderbilt','Hot Rods of Garlic-Inserted Rattlesnake Roast with Mentholated Ravioli Nugs Hangin'' Ten in a Horseradish Coulis');
INSERT INTO menu VALUES(74,'The Karen Carpenter','Spicy Italian Pecan-Smashed Bacon Patties with Purse-Snatched Wheat Germ Portions Partially Submerged in a Mr. Pibb Gravy');
INSERT INTO menu VALUES(75,'All the Pretty Horses','Peak Season Gluten-Hammered Rattlesnake Loaf with Vaped Broccoli Raab Tidbits Drowning in a Surge Hearse');
INSERT INTO menu VALUES(76,'40 oz to Freedom','Guy''s Famous Lipid-Smattered Rattlesnake Enchiladas with Windswept Ravioli Jobbers Drowning in a White Zin Aioli');
INSERT INTO menu VALUES(77,'Drops of Jupiter','French Canadian Clam-Thrashed Eel Tips with Pan Seared Sweet Potato Jammers Marinated in a Powerade Au Jus');
INSERT INTO menu VALUES(78,'Tijuana Flavorwave','Spicy Italian Pecan-Anointed Rattlesnake Tips with Fire Bruised Jackfruit Flapjacks Drowning in a Watermelon Four Loko Hollandaise');
INSERT INTO menu VALUES(79,'Snakes on a Plate','Jack Daniels Garlic-Mauled Duckling Hunk with Vaped Asparagus Nugs Crying for Help in a Bongwater Bearnaise');
INSERT INTO menu VALUES(80,'What I Got','Fancy Cut Chipotle-Anointed Bacon Cutlets with Croc-Stomped Cauliflower Portions Curdling in a Sunny D Jacuzzi');
INSERT INTO menu VALUES(81,'All the Pretty Horses','Pittsburgh''s Finest MSG-Thrashed Falafel Patties with Triple-Fried Sweet Potato Flapjacks Frothing in a GoGurt Donkey Sauce');
INSERT INTO menu VALUES(82,'The Truth About Cats and Dogs','Olde Tyme Garlic-Thrusted Corgi Tips with Steamed Walnut Jobbers Curdling in a Mountain Dew Code Red Demi-glace');
INSERT INTO menu VALUES(83,'Don''t Tread on Meat','Guypocalyptic Pecan-Fisted Falafel Burger with Triple-Fried Quinoa Grapplers Hangin'' Ten in a Clarified Lard Hollandaise');
INSERT INTO menu VALUES(84,'PT Cruised','Uncle Kracker''s Signature Cheddar-Murdered Eel Shank with Purse-Snatched Quinoa Griplets Crying for Help in a 5-Hour Energy Hearse');
INSERT INTO menu VALUES(85,'BeefTech','Pittsburgh''s Finest Havarti-Mauled Manatee Slab with Pan Seared Quinoa Units Implemented in a Queso Coulis');
INSERT INTO menu VALUES(86,'Your Funeral','Partytime Gruyere-Smattered Black Rhino Tips with Taste-tosterone Marinated Broccoli Raab Jobbers Ripping a Bass Solo in a 5-Hour Energy Hollandaise');
INSERT INTO menu VALUES(87,'Snakes on a Plate','Spicy Italian Chipotle-Thrusted Duckling Enchiladas with Fry-olated Butternut Squash Nugs Stroking Out in a White Zin Jacuzzi');
INSERT INTO menu VALUES(88,'Guyway to Heaven','Guy''s Own MSG-Thrashed Manatee Bits with Fire Bruised Zucchini Nugs Sevendusted in a Capri Sun Safari Fruits Holocaust');
INSERT INTO menu VALUES(89,'The Treat Williams','Spicy Italian Crunch-Inserted Beef Hunk with Steamed Quinoa Nugs Frothing in a Horseradish Bearnaise');
INSERT INTO menu VALUES(90,'What I Got','Guy''s Famous Crunch-Smattered Lamb Cutlets with Vaped Walnut Flapjacks Stroking Out in a Zima Au Jus');
INSERT INTO menu VALUES(91,'Your Funeral','Uncle Kracker''s Signature Gluten-Smashed Rattlesnake Bits with Fry-olated Ravioli Jammers Ripping a Bass Solo in a GoGurt Gravy');
INSERT INTO menu VALUES(92,'Lady in Red','Laser Julienned Onion-Thrashed Manatee Enchiladas with Finger-Rolled Walnut Clumps Implemented in a GoGurt Hollandaise');
INSERT INTO menu VALUES(93,'Jingle All the Way','Olde Tyme Crunch-Smashed Black Rhino Flatbread with Fire Bruised Asparagus Griplets Stroking Out in a Stroh''s Flavor Puddle');
INSERT INTO menu VALUES(94,'Turn Down for What','Guypocalyptic Lipid-Fisted Corgi Tips with Galvanized Wheat Germ Jobbers Curdling in a Watermelon Four Loko Coulis');
INSERT INTO menu VALUES(95,'Two Grills One Cup','French Canadian Pecan-Thrashed Black Rhino Loaf with Windswept Jackfruit Flapjacks Twerking in a Queso Bouillabaisse');
INSERT INTO menu VALUES(96,'Jingle All the Way','42 Fluid Ounces of Gluten-Tweaked Baby Seal Doggers with Triple-Fried Sweet Potato Nugs Crucified in a 5-Hour Energy Flavor Puddle');
INSERT INTO menu VALUES(97,'Lemonparty','42 Fluid Ounces of Pimento-Thrashed Octopus Tips with Triple-Fried Zucchini Jammers Floating in a Queso Hollandaise');
INSERT INTO menu VALUES(98,'Two Grills One Cup','Jack Daniels Cheddar-Groped Eel Doggers with Galvanized Sweet Potato Grapplers Coming of Age in a Capri Sun Safari Fruits Hearse');
INSERT INTO menu VALUES(99,'Lemonparty','Spicy Italian Gluten-Fisted Lamb Doggers with Fire Bruised Zucchini Nugs Coming of Age in a Spray Butter Au Jus');
INSERT INTO menu VALUES(100,'The Truth About Cats and Dogs','Laser Julienned Gruyere-Mauled Eel Bits with Galvanized Snow Pea Griplets Holding Their Own in a Sunny D Hollandaise');
INSERT INTO menu VALUES(101,'Tits L''Amour','Spicy Italian Onion-Groped Manatee Loaf with Triple-Fried Wheat Germ Flapjacks Implemented in a Powerade Au Jus');
INSERT INTO menu VALUES(102,'Three Men and a Little Gravy','Uncle Kracker''s Signature Garlic-Inserted Rattlesnake Flatbread with Fry-olated Edamame Jammers Coming of Age in a Mr. Pibb Donkey Sauce');
INSERT INTO menu VALUES(103,'The Truth About Cats and Dogs','Guy''s Famous Havarti-Fisted Corgi Roast with Fry-olated Edamame Clumps Crucified in a Capri Sun Safari Fruits Coulis');
INSERT INTO menu VALUES(104,'Two Grills One Cup','Pittsburgh''s Finest Pecan-Mauled Baby Seal Slab with Fingerbanged Edamame Units Sevendusted in a 5-Hour Energy Reduction');
INSERT INTO menu VALUES(105,'The Karen Carpenter','Guy''s Own Chipotle-Murdered Beef Burger with Pan Seared Zucchini Flapjacks Mingling in a Clotted Cream Demi-glace');
INSERT INTO menu VALUES(106,'That''s What She Said','Uncle Kracker''s Signature Gluten-Fisted Veal Tips with Finger-Rolled Jackfruit Nugs Fornicating in a Sunny D Hearse');
INSERT INTO menu VALUES(107,'40 oz to Freedom','Uncle Kracker''s Signature Pimento-Creamed Veal Cutlets with Taste-tosterone Marinated Snow Pea Clumps Crucified in a Queso Au Jus');
INSERT INTO menu VALUES(108,'Who Let the Dogs In?','Guypocalyptic Pecan-Murdered Corgi Cutlets with Vaped Sweet Potato Clumps Fornicating in a 5-Hour Energy Hearse');
INSERT INTO menu VALUES(109,'Juggaloaf','Spicy Italian Onion-Groped Duckling Slab with Windswept Butternut Squash Griplets Crying for Help in a Sunny D Flavor Puddle');
INSERT INTO menu VALUES(110,'Juggaloaf','Uncle Kracker''s Signature Acai-Blasted Beef Tips with Finger-Rolled Butternut Squash Flapjacks Crying for Help in a Capri Sun Safari Fruits Gravy');
INSERT INTO menu VALUES(111,'Snakes on a Plate','Olde Tyme Pimento-Thrashed Lamb Enchiladas with Purse-Snatched Edamame Tidbits Crucified in a Queso Reduction');
INSERT INTO menu VALUES(112,'Madea''s Family Reunion','Laser Julienned Pecan-Blasted Falafel Doggers with Steamed Ravioli Griplets Drowning in a Mountain Dew Code Red Jacuzzi');
INSERT INTO menu VALUES(113,'The Eddie Money Shot','Fancy Cut Pecan-Hammered Manatee Patties with Fire Bruised Snow Pea Griplets Waterboarded in a Queso Bouillabaisse');
INSERT INTO menu VALUES(114,'What I Got','All-American Lipid-Inserted Bacon Hunk with Pan Seared Butternut Squash Clumps Sevendusted in a Sunny D Gravy');
INSERT INTO menu VALUES(115,'The Karen Carpenter','Guypocalyptic Gluten-Groped Beef Bits with Pan Seared Wheat Germ Portions Stroking Out in a Mountain Dew Code Red Bearnaise');
INSERT INTO menu VALUES(116,'Who Let the Dogs In?','Olde Tyme Panko-Creamed Bacon Enchiladas with Powdered Wheat Germ Jobbers Twerking in a Sunny D Reduction');
INSERT INTO menu VALUES(117,'Juggaloaf','Guy''s Own Gruyere-Inserted Pork Doggers with Taste-tosterone Marinated Wheat Germ Units Fornicating in a Powerade Bouillabaisse');
INSERT INTO menu VALUES(118,'The Dealbreaker','Uncle Kracker''s Signature Crunch-Blasted Manatee Patties with Pan Seared Cauliflower Jammers Crying for Help in a Capri Sun Safari Fruits Au Jus');
INSERT INTO menu VALUES(119,'C. Thomas Howell IV','Spicy Italian Panko-Hammered Lamb Shank with Finger-Rolled Edamame Portions Holding Their Own in a Powerade Demi-glace');
INSERT INTO menu VALUES(120,'Hong','Hot Rods of Garlic-Smattered Veal Cutlets with Vaped Snow Pea Portions Implemented in a Clotted Cream Bearnaise');
INSERT INTO menu VALUES(121,'Turn Down for What','Guy''s Own Havarti-Anointed Beef Slab with Croc-Stomped Cauliflower Jobbers Mingling in an Arizona Iced Tea Hearse');
INSERT INTO menu VALUES(122,'What I Got','Guy''s Own MSG-Thrusted Duckling Shank with Powdered Jackfruit Portions Curdling in a Mr. Pibb Hearse');
INSERT INTO menu VALUES(123,'The Vanderbilt','Rock and Roll Clam-Smattered Octopus Loaf with Fingerbanged Edamame Tidbits Frothing in a Tampico Aioli');
INSERT INTO menu VALUES(124,'The Schneider','Hot Rods of Chipotle-Thrashed Veal Bits with Broasted Butternut Squash Rippers Crucified in a Horseradish Flavor Puddle');
INSERT INTO menu VALUES(125,'What I Got','Guypocalyptic Pecan-Thrusted Black Rhino Patties with Vaped Sweet Potato Clumps Partying ''til Dawn in a Horseradish Donkey Sauce');
INSERT INTO menu VALUES(126,'Stop or My Mom Will Shart','Partytime Cool Ranch-Tweaked Pork Flatbread with Fire Bruised Asparagus Griplets Marinated in a 5-Hour Energy Bouillabaisse');
INSERT INTO menu VALUES(127,'Drops of Jupiter','Hot Rods of Chipotle-Smashed Bacon Roast with Triple-Fried Jackfruit Nugs Coming of Age in a GoGurt Gravy');
INSERT INTO menu VALUES(128,'Lemonparty','Partytime Pecan-Hammered Corgi Loaf with Broasted Snow Pea Rippers Floating in a Mr. Pibb Jacuzzi');
INSERT INTO menu VALUES(129,'Gleaming the Cube Steak','All-American Lipid-Smashed Duckling Shank with Fry-olated Butternut Squash Jammers Implemented in a Mountain Dew Code Red Au Jus');
INSERT INTO menu VALUES(130,'Juggaloaf','French Canadian Clam-Hammered Veal Roast with Fry-olated Butternut Squash Jammers Crying for Help in a Powerade Reduction');
INSERT INTO menu VALUES(131,'The Dealbreaker','Olde Tyme Pecan-Thrusted Corgi Bits with Pan Seared Broccoli Raab Units Twerking in a Queso Sauce');
INSERT INTO menu VALUES(132,'The Schneider','All-American Chipotle-Murdered Falafel Bits with Fingerbanged Quinoa Griplets Coming of Age in a GoGurt Bearnaise');
INSERT INTO menu VALUES(133,'The Bringer of Pain to Your Face','Uncle Kracker''s Signature Acai-Murdered Manatee Enchiladas with Broasted Zucchini Jammers Ripping a Bass Solo in a Horseradish Bouillabaisse');
INSERT INTO menu VALUES(134,'How Do You Talk to an Angel?','Uncle Kracker''s Signature Clam-Drilled Baby Seal Patties with Finger-Rolled Zucchini Tidbits Curdling in a Powerade Demi-glace');
INSERT INTO menu VALUES(135,'Shake That Bear','Uncle Kracker''s Signature Lipid-Fisted Pancetta Bits with Fry-olated Sweet Potato Flapjacks Drowning in a Powerade Hearse');
INSERT INTO menu VALUES(136,'Lemonparty','All-American MSG-Smattered Manatee Tips with Thrice-Baked Cauliflower Clumps Crying for Help in a Surge Demi-glace');
INSERT INTO menu VALUES(137,'Three Men and a Little Gravy','French Canadian Garlic-Fisted Pancetta Roast with Steamed Ravioli Flapjacks Stroking Out in a Mr. Pibb Flavor Puddle');
INSERT INTO menu VALUES(138,'C. Thomas Howell IV','Spicy Italian Crunch-Thrusted Pork Bits with Windswept Asparagus Units Ripping a Bass Solo in a Watermelon Four Loko Demi-glace');
INSERT INTO menu VALUES(139,'The Schneider','Fancy Cut Cheddar-Thrashed Black Rhino Bits with Fry-olated Walnut Nugs Slam Dunked in a Surge Donkey Sauce');
INSERT INTO menu VALUES(140,'Shake That Bear','Partytime Panko-Hammered Pork Patties with Pan Seared Ravioli Portions Holding Their Own in a Clarified Lard Donkey Sauce');
INSERT INTO menu VALUES(141,'Snakes on a Plate','42 Fluid Ounces of Cheddar-Anointed Manatee Burger with Vaped Broccoli Raab Portions Crucified in a Surge Hollandaise');
INSERT INTO menu VALUES(142,'We Need To Talk About Kevin','Laser Julienned Havarti-Fisted Falafel Tips with Steamed Jackfruit Grapplers Curdling in a Mr. Pibb Hearse');
INSERT INTO menu VALUES(143,'Who Let the Dogs In?','Guy''s Famous Pecan-Murdered Baby Seal Roast with Steamed Wheat Germ Grapplers Slam Dunked in a 5-Hour Energy Aioli');
INSERT INTO menu VALUES(144,'The Frosting of the Tips','Fancy Cut MSG-Smattered Veal Flatbread with Purse-Snatched Jackfruit Rippers Floating in a White Zin Flavor Puddle');
INSERT INTO menu VALUES(145,'Tijuana Flavorwave','Guypocalyptic Havarti-Creamed Bison Tips with Windswept Snow Pea Jobbers Waterboarded in a GoGurt Reduction');
INSERT INTO menu VALUES(146,'Don''t Tread on Meat','Guy''s Famous Panko-Mauled Beef Patties with Fry-olated Zucchini Jobbers Partially Submerged in a Capri Sun Safari Fruits Bearnaise');
INSERT INTO menu VALUES(147,'Who Let the Dogs In?','Peak Season Gruyere-Drilled Octopus Bits with Steamed Jackfruit Units Twerking in a Queso Demi-glace');
INSERT INTO menu VALUES(148,'BeefTech','All-American Pimento-Inserted Manatee Doggers with Thrice-Baked Ravioli Nugs Floating in a Surge Aioli');
INSERT INTO menu VALUES(149,'Juggaloaf','French Canadian Crunch-Tweaked Pancetta Doggers with Triple-Fried Zucchini Rippers Implemented in a White Zin Donkey Sauce');
INSERT INTO menu VALUES(150,'The Eddie Money Shot','Laser Julienned Garlic-Thrashed Bison Enchiladas with Triple-Fried Butternut Squash Rippers Floating in a Zima Hollandaise');
INSERT INTO menu VALUES(151,'Juggaloaf','Olde Tyme Clam-Tweaked Baby Seal Hunk with Croc-Stomped Cauliflower Jobbers Holding Their Own in a Bongwater Holocaust');
INSERT INTO menu VALUES(152,'What I Got','Spicy Italian Onion-Thrashed Black Rhino Slab with Broasted Sweet Potato Griplets Holding Their Own in a Watermelon Four Loko Sauce');
INSERT INTO menu VALUES(153,'Lemonparty','Hot Rods of MSG-Drilled Black Rhino Flatbread with Croc-Stomped Broccoli Raab Portions Mingling in a Capri Sun Safari Fruits Holocaust');
INSERT INTO menu VALUES(154,'The Bringer of Pain to Your Face','Laser Julienned Gluten-Fisted Veal Burger with Croc-Stomped Edamame Flapjacks Partying ''til Dawn in a Powerade Holocaust');
INSERT INTO menu VALUES(155,'Shake That Bear','42 Fluid Ounces of Lipid-Creamed Lamb Doggers with Powdered Edamame Portions Waterboarded in a Clotted Cream Sauce');
INSERT INTO menu VALUES(156,'The Dealbreaker','Fancy Cut Panko-Fisted Manatee Bits with Fingerbanged Snow Pea Grapplers Floating in a Sunny D Gravy');
INSERT INTO menu VALUES(157,'Snakes on a Plate','Fancy Cut Chipotle-Creamed Lamb Cutlets with Powdered Zucchini Rippers Partially Submerged in a Horseradish Bearnaise');
INSERT INTO menu VALUES(158,'What I Got','Jack Daniels Acai-Mauled Bacon Flatbread with Finger-Rolled Cauliflower Tidbits Coming of Age in a Queso Demi-glace');
INSERT INTO menu VALUES(159,'Lemonparty','Guypocalyptic Garlic-Fisted Falafel Burger with Powdered Broccoli Raab Nugs Stroking Out in a Sunny D Jacuzzi');
INSERT INTO menu VALUES(160,'Your Funeral','French Canadian Gluten-Tweaked Pork Flatbread with Galvanized Broccoli Raab Jammers Marinated in a White Zin Coulis');
INSERT INTO menu VALUES(161,'The Lou Diamond Phillips','Olde Tyme Clam-Smattered Falafel Bits with Finger-Rolled Sweet Potato Jammers Coming of Age in a Horseradish Bearnaise');
INSERT INTO menu VALUES(162,'Juggaloaf','Uncle Kracker''s Signature Gluten-Thrashed Corgi Hunk with Fire Bruised Jackfruit Griplets Partying ''til Dawn in a Powerade Hollandaise');
INSERT INTO menu VALUES(163,'Some Gave All','French Canadian MSG-Hammered Corgi Cutlets with Fingerbanged Cauliflower Clumps Stroking Out in a Zima Coulis');
INSERT INTO menu VALUES(164,'The Truth About Cats and Dogs','All-American Pecan-Smattered Bacon Loaf with Broasted Wheat Germ Units Crying for Help in a Mountain Dew Code Red Jacuzzi');
INSERT INTO menu VALUES(165,'Lemonparty','Guypocalyptic Clam-Murdered Eel Loaf with Purse-Snatched Butternut Squash Nugs Crucified in a GoGurt Aioli');
INSERT INTO menu VALUES(166,'Some Gave All','French Canadian Gluten-Creamed Lamb Hunk with Fingerbanged Sweet Potato Flapjacks Hangin'' Ten in a Surge Bearnaise');
INSERT INTO menu VALUES(167,'The Dealbreaker','Jack Daniels Onion-Anointed Manatee Shank with Triple-Fried Ravioli Jammers Coming of Age in a Stroh''s Bearnaise');
INSERT INTO menu VALUES(168,'PT Cruised','Guy''s Own Havarti-Drilled Black Rhino Flatbread with Taste-tosterone Marinated Quinoa Clumps Mingling in a Tampico Bouillabaisse');
INSERT INTO menu VALUES(169,'Dr. T and the Women','French Canadian Crunch-Fisted Eel Shank with Triple-Fried Sweet Potato Jobbers Frothing in a Horseradish Holocaust');
INSERT INTO menu VALUES(170,'Lady in Red','Jack Daniels Crunch-Tweaked Veal Doggers with Purse-Snatched Quinoa Portions Mingling in a Powerade Donkey Sauce');
INSERT INTO menu VALUES(171,'Dr. T and the Women','Peak Season Acai-Smashed Manatee Slab with Purse-Snatched Cauliflower Tidbits Hangin'' Ten in a White Zin Jacuzzi');
INSERT INTO menu VALUES(172,'That''s What She Said','42 Fluid Ounces of Garlic-Thrusted Manatee Enchiladas with Croc-Stomped Quinoa Units Marinated in a Spray Butter Demi-glace');
INSERT INTO menu VALUES(173,'The Eddie Money Shot','Uncle Kracker''s Signature Chipotle-Hammered Bacon Enchiladas with Finger-Rolled Ravioli Griplets Curdling in a Queso Donkey Sauce');
INSERT INTO menu VALUES(174,'40 oz to Freedom','42 Fluid Ounces of MSG-Smashed Bison Doggers with Windswept Zucchini Units Curdling in a GoGurt Jacuzzi');
INSERT INTO menu VALUES(175,'Snakes on a Plate','Jack Daniels Pimento-Blasted Bison Enchiladas with Powdered Snow Pea Units Partially Submerged in a Tampico Bearnaise');
INSERT INTO menu VALUES(176,'Who Let the Dogs In?','Fancy Cut Chipotle-Hammered Manatee Cutlets with Fingerbanged Asparagus Flapjacks Crucified in a Stroh''s Hollandaise');
INSERT INTO menu VALUES(177,'Lady in Red','Fancy Cut Garlic-Hammered Corgi Slab with Fingerbanged Ravioli Jammers Waterboarded in a GoGurt Holocaust');
INSERT INTO menu VALUES(178,'Drops of Jupiter','Guy''s Famous Cool Ranch-Drilled Manatee Roast with Triple-Fried Cauliflower Grapplers Curdling in a Sunny D Coulis');
INSERT INTO menu VALUES(179,'Dr. T and the Women','Guy''s Famous Cheddar-Drilled Duckling Slab with Vaped Asparagus Nugs Floating in a White Zin Coulis');
INSERT INTO menu VALUES(180,'Juggaloaf','Partytime Clam-Thrusted Bacon Shank with Taste-tosterone Marinated Walnut Jammers Holding Their Own in a GoGurt Gravy');
INSERT INTO menu VALUES(181,'Snakes on a Plate','Guy''s Famous Cool Ranch-Fisted Baby Seal Shank with Thrice-Baked Zucchini Grapplers Coming of Age in a Watermelon Four Loko Hearse');
INSERT INTO menu VALUES(182,'Drops of Jupiter','Fancy Cut Clam-Inserted Eel Roast with Purse-Snatched Snow Pea Clumps Sevendusted in a Watermelon Four Loko Gravy');
INSERT INTO menu VALUES(183,'Tits L''Amour','Pittsburgh''s Finest MSG-Murdered Rattlesnake Tips with Finger-Rolled Butternut Squash Clumps Holding Their Own in a Clotted Cream Hearse');
INSERT INTO menu VALUES(184,'Just the Tip','Spicy Italian Onion-Tweaked Pork Loaf with Galvanized Jackfruit Rippers Frothing in a Tampico Donkey Sauce');
INSERT INTO menu VALUES(185,'Some Gave All','Rock and Roll Acai-Fisted Bison Hunk with Pan Seared Butternut Squash Portions Ripping a Bass Solo in a Queso Hollandaise');
INSERT INTO menu VALUES(186,'The Treat Williams','Guy''s Own Pimento-Thrashed Veal Bits with Mentholated Quinoa Tidbits Waterboarded in a Surge Bouillabaisse');
INSERT INTO menu VALUES(187,'The Karen Carpenter','Fancy Cut Clam-Groped Manatee Slab with Vaped Ravioli Units Mingling in a Horseradish Sauce');
INSERT INTO menu VALUES(188,'40 oz to Freedom','Partytime Pecan-Inserted Octopus Loaf with Steamed Cauliflower Clumps Crucified in a Powerade Au Jus');
INSERT INTO menu VALUES(189,'Hong','Guypocalyptic Onion-Blasted Duckling Hunk with Purse-Snatched Broccoli Raab Flapjacks Holding Their Own in a Clarified Lard Gravy');
INSERT INTO menu VALUES(190,'The Ghost Dad','Laser Julienned Cool Ranch-Murdered Veal Enchiladas with Fingerbanged Asparagus Nugs Crying for Help in a Watermelon Four Loko Bouillabaisse');
INSERT INTO menu VALUES(191,'The Frosting of the Tips','Guypocalyptic Cheddar-Inserted Falafel Slab with Powdered Broccoli Raab Units Marinated in a Zima Holocaust');
INSERT INTO menu VALUES(192,'Jingle All the Way','Guypocalyptic Acai-Smattered Falafel Patties with Broasted Quinoa Portions Drowning in a Surge Donkey Sauce');
INSERT INTO menu VALUES(193,'Turn Down for What','Pittsburgh''s Finest Clam-Creamed Bacon Slab with Croc-Stomped Cauliflower Rippers Waterboarded in a Capri Sun Safari Fruits Au Jus');
INSERT INTO menu VALUES(194,'Your Funeral','Rock and Roll Gruyere-Inserted Veal Enchiladas with Taste-tosterone Marinated Snow Pea Jobbers Mingling in a Surge Gravy');
INSERT INTO menu VALUES(195,'Don''t Tread on Meat','Guypocalyptic Garlic-Anointed Black Rhino Roast with Vaped Edamame Nugs Drowning in a Mountain Dew Code Red Reduction');
INSERT INTO menu VALUES(196,'40 oz to Freedom','Rock and Roll Cool Ranch-Smashed Baby Seal Flatbread with Fry-olated Broccoli Raab Jammers Stroking Out in a Mr. Pibb Hollandaise');
INSERT INTO menu VALUES(197,'The Lou Diamond Phillips','Guy''s Own Cheddar-Groped Pancetta Burger with Taste-tosterone Marinated Asparagus Griplets Mingling in a White Zin Hollandaise');
INSERT INTO menu VALUES(198,'Lady in Red','French Canadian Panko-Anointed Falafel Shank with Powdered Sweet Potato Portions Curdling in a Horseradish Jacuzzi');
INSERT INTO menu VALUES(199,'The Ghost Dad','Guy''s Famous Pecan-Mauled Rattlesnake Loaf with Thrice-Baked Ravioli Flapjacks Crucified in a White Zin Gravy');
INSERT INTO menu VALUES(200,'The Treat Williams','Fancy Cut Garlic-Tweaked Eel Loaf with Steamed Snow Pea Flapjacks Coming of Age in a GoGurt Au Jus');
INSERT INTO menu VALUES(201,'BeefTech','Hot Rods of Acai-Blasted Beef Hunk with Mentholated Cauliflower Jammers Floating in a White Zin Sauce');
INSERT INTO menu VALUES(202,'Gleaming the Cube Steak','Guypocalyptic Pecan-Smashed Baby Seal Doggers with Broasted Quinoa Griplets Partying ''til Dawn in a Surge Jacuzzi');
INSERT INTO menu VALUES(203,'C. Thomas Howell IV','Partytime Cool Ranch-Smattered Rattlesnake Flatbread with Mentholated Edamame Jammers Partying ''til Dawn in a Clarified Lard Flavor Puddle');
INSERT INTO menu VALUES(204,'Lady in Red','French Canadian Lipid-Thrusted Manatee Burger with Steamed Snow Pea Griplets Ripping a Bass Solo in an Arizona Iced Tea Bouillabaisse');
INSERT INTO menu VALUES(205,'The Vanderbilt','Jack Daniels Crunch-Tweaked Eel Enchiladas with Mentholated Broccoli Raab Grapplers Ripping a Bass Solo in a Stroh''s Jacuzzi');
INSERT INTO menu VALUES(206,'Three Men and a Little Gravy','Uncle Kracker''s Signature Panko-Drilled Corgi Patties with Triple-Fried Sweet Potato Jammers Coming of Age in a Clotted Cream Aioli');
INSERT INTO menu VALUES(207,'Madea''s Family Reunion','Peak Season Clam-Mauled Lamb Loaf with Steamed Sweet Potato Tidbits Slam Dunked in a Zima Bearnaise');
INSERT INTO menu VALUES(208,'Three Men and a Little Gravy','All-American Gluten-Tweaked Duckling Patties with Triple-Fried Sweet Potato Rippers Floating in a Spray Butter Reduction');
INSERT INTO menu VALUES(209,'We Need To Talk About Kevin','All-American Gluten-Smattered Black Rhino Hunk with Fire Bruised Snow Pea Grapplers Hangin'' Ten in a Bongwater Donkey Sauce');
INSERT INTO menu VALUES(210,'Snakes on a Plate','Jack Daniels Cool Ranch-Drilled Pork Cutlets with Mentholated Ravioli Flapjacks Drowning in a Watermelon Four Loko Holocaust');
INSERT INTO menu VALUES(211,'All the Pretty Horses','All-American Crunch-Murdered Octopus Cutlets with Vaped Ravioli Jammers Floating in a 5-Hour Energy Aioli');
INSERT INTO menu VALUES(212,'Two Grills One Cup','Laser Julienned Crunch-Inserted Eel Roast with Windswept Edamame Nugs Partially Submerged in a Stroh''s Jacuzzi');
INSERT INTO menu VALUES(213,'The Lou Diamond Phillips','French Canadian Clam-Mauled Octopus Roast with Powdered Asparagus Jammers Stroking Out in an Arizona Iced Tea Hearse');
INSERT INTO menu VALUES(214,'How Do You Talk to an Angel?','Jack Daniels Acai-Murdered Beef Shank with Steamed Zucchini Rippers Crying for Help in a Mountain Dew Code Red Holocaust');
INSERT INTO menu VALUES(215,'How Do You Talk to an Angel?','Hot Rods of Lipid-Tweaked Manatee Burger with Purse-Snatched Butternut Squash Grapplers Coming of Age in a Tampico Reduction');
INSERT INTO menu VALUES(216,'That''s What She Said','Olde Tyme Clam-Blasted Bacon Patties with Galvanized Butternut Squash Jobbers Partially Submerged in a Capri Sun Safari Fruits Gravy');
INSERT INTO menu VALUES(217,'Lady in Red','42 Fluid Ounces of Pimento-Drilled Lamb Roast with Galvanized Asparagus Portions Marinated in a Zima Coulis');
INSERT INTO menu VALUES(218,'Benghazi!','Fancy Cut Crunch-Anointed Octopus Bits with Galvanized Jackfruit Nugs Hangin'' Ten in a Capri Sun Safari Fruits Aioli');
INSERT INTO menu VALUES(219,'Your Funeral','Fancy Cut Crunch-Creamed Octopus Loaf with Fire Bruised Snow Pea Jobbers Partially Submerged in a Spray Butter Aioli');
INSERT INTO menu VALUES(220,'How Do You Talk to an Angel?','Guypocalyptic Pecan-Murdered Duckling Doggers with Powdered Edamame Grapplers Marinated in a Stroh''s Hollandaise');
INSERT INTO menu VALUES(221,'Don''t Tread on Meat','42 Fluid Ounces of Panko-Hammered Beef Roast with Windswept Ravioli Rippers Holding Their Own in a 5-Hour Energy Sauce');
INSERT INTO menu VALUES(222,'The Frosting of the Tips','Peak Season Havarti-Drilled Pancetta Cutlets with Triple-Fried Sweet Potato Jobbers Mingling in a Surge Bearnaise');
INSERT INTO menu VALUES(223,'Lemonparty','Peak Season Pimento-Smattered Bacon Shank with Triple-Fried Ravioli Flapjacks Crucified in a 5-Hour Energy Reduction');
INSERT INTO menu VALUES(224,'BeefTech','All-American Gruyere-Murdered Duckling Patties with Steamed Jackfruit Tidbits Mingling in a Powerade Flavor Puddle');
INSERT INTO menu VALUES(225,'How Do You Talk to an Angel?','Olde Tyme Acai-Murdered Pancetta Hunk with Powdered Broccoli Raab Clumps Stroking Out in a Queso Reduction');
INSERT INTO menu VALUES(226,'Who Let the Dogs In?','French Canadian Garlic-Smashed Pork Loaf with Steamed Cauliflower Flapjacks Stroking Out in a Spray Butter Sauce');
INSERT INTO menu VALUES(227,'The Schneider','French Canadian Pimento-Creamed Baby Seal Loaf with Broasted Zucchini Tidbits Crucified in a Sunny D Coulis');
INSERT INTO menu VALUES(228,'The Bringer of Pain to Your Face','Spicy Italian Cheddar-Creamed Manatee Slab with Powdered Jackfruit Units Crucified in a Clotted Cream Reduction');
INSERT INTO menu VALUES(229,'Juggaloaf','Jack Daniels Chipotle-Mauled Pancetta Doggers with Triple-Fried Jackfruit Jammers Crying for Help in an Arizona Iced Tea Holocaust');
INSERT INTO menu VALUES(230,'That''s What She Said','Hot Rods of Panko-Blasted Black Rhino Shank with Fire Bruised Walnut Clumps Waterboarded in an Arizona Iced Tea Bouillabaisse');
INSERT INTO menu VALUES(231,'Shake That Bear','Guy''s Famous Onion-Murdered Falafel Shank with Windswept Walnut Rippers Holding Their Own in a White Zin Reduction');
INSERT INTO menu VALUES(232,'BeefTech','All-American Gluten-Thrusted Bison Tips with Triple-Fried Jackfruit Jobbers Mingling in a Queso Hollandaise');
INSERT INTO menu VALUES(233,'Two Grills One Cup','42 Fluid Ounces of Gluten-Fisted Corgi Loaf with Fire Bruised Jackfruit Nugs Twerking in a Clotted Cream Hearse');
INSERT INTO menu VALUES(234,'That''s What She Said','Laser Julienned Garlic-Hammered Falafel Enchiladas with Broasted Ravioli Tidbits Drowning in a Mountain Dew Code Red Au Jus');
INSERT INTO menu VALUES(235,'Two Grills One Cup','Pittsburgh''s Finest Crunch-Smashed Black Rhino Tips with Finger-Rolled Jackfruit Grapplers Floating in an Arizona Iced Tea Sauce');
INSERT INTO menu VALUES(236,'The Ghost Dad','Hot Rods of Crunch-Thrashed Octopus Roast with Mentholated Broccoli Raab Jobbers Slam Dunked in a Clarified Lard Bouillabaisse');
INSERT INTO menu VALUES(237,'Benghazi!','Laser Julienned Crunch-Smattered Black Rhino Flatbread with Triple-Fried Sweet Potato Portions Waterboarded in a Horseradish Gravy');
INSERT INTO menu VALUES(238,'Hong','All-American Crunch-Fisted Bison Doggers with Finger-Rolled Butternut Squash Nugs Twerking in a Queso Coulis');
INSERT INTO menu VALUES(239,'Your Funeral','Olde Tyme Pimento-Drilled Veal Roast with Taste-tosterone Marinated Sweet Potato Rippers Implemented in a Surge Sauce');
INSERT INTO menu VALUES(240,'That''s What She Said','Rock and Roll Lipid-Thrashed Octopus Hunk with Powdered Cauliflower Grapplers Hangin'' Ten in a Clotted Cream Donkey Sauce');
INSERT INTO menu VALUES(241,'Snakes on a Plate','42 Fluid Ounces of Gruyere-Inserted Duckling Loaf with Powdered Quinoa Jammers Hangin'' Ten in a Watermelon Four Loko Donkey Sauce');
INSERT INTO menu VALUES(242,'Hong','French Canadian Onion-Drilled Black Rhino Slab with Taste-tosterone Marinated Asparagus Grapplers Marinated in an Arizona Iced Tea Sauce');
INSERT INTO menu VALUES(243,'The Truth About Cats and Dogs','French Canadian Garlic-Hammered Eel Patties with Steamed Zucchini Rippers Ripping a Bass Solo in a Zima Donkey Sauce');
INSERT INTO menu VALUES(244,'BeefTech','Jack Daniels Lipid-Fisted Pork Shank with Purse-Snatched Cauliflower Tidbits Hangin'' Ten in a Horseradish Demi-glace');
INSERT INTO menu VALUES(245,'The Lou Diamond Phillips','Uncle Kracker''s Signature Gluten-Smattered Black Rhino Slab with Pan Seared Jackfruit Clumps Crucified in a Clotted Cream Aioli');
INSERT INTO menu VALUES(246,'Benghazi!','Spicy Italian Garlic-Murdered Black Rhino Shank with Galvanized Jackfruit Jobbers Twerking in a Stroh''s Aioli');
INSERT INTO menu VALUES(247,'Snakes on a Plate','Pittsburgh''s Finest Onion-Thrashed Black Rhino Patties with Galvanized Edamame Nugs Ripping a Bass Solo in an Arizona Iced Tea Hearse');
INSERT INTO menu VALUES(248,'That''s What She Said','Laser Julienned Cheddar-Thrusted Pork Hunk with Broasted Quinoa Rippers Stroking Out in a Clotted Cream Gravy');
INSERT INTO menu VALUES(249,'My Giant','Rock and Roll Pimento-Hammered Manatee Tips with Steamed Edamame Portions Slam Dunked in a Spray Butter Donkey Sauce');
INSERT INTO menu VALUES(250,'Drops of Jupiter','Peak Season Onion-Hammered Eel Patties with Galvanized Sweet Potato Portions Mingling in a Surge Reduction');
INSERT INTO menu VALUES(251,'Guyway to Heaven','42 Fluid Ounces of Clam-Thrusted Rattlesnake Doggers with Triple-Fried Wheat Germ Nugs Partially Submerged in an Arizona Iced Tea Reduction');
INSERT INTO menu VALUES(252,'Stop or My Mom Will Shart','Hot Rods of Pecan-Mauled Pork Roast with Triple-Fried Snow Pea Jammers Twerking in a Bongwater Flavor Puddle');
INSERT INTO menu VALUES(253,'The Lou Diamond Phillips','All-American Gruyere-Smattered Black Rhino Loaf with Broasted Cauliflower Griplets Implemented in a Spray Butter Donkey Sauce');
INSERT INTO menu VALUES(254,'My Giant','Partytime Garlic-Inserted Bacon Bits with Broasted Ravioli Flapjacks Coming of Age in a Mr. Pibb Hearse');
INSERT INTO menu VALUES(255,'The Vanderbilt','Hot Rods of Crunch-Murdered Veal Loaf with Mentholated Butternut Squash Griplets Ripping a Bass Solo in a Zima Donkey Sauce');
INSERT INTO menu VALUES(256,'The Lou Diamond Phillips','Spicy Italian Lipid-Thrashed Bacon Hunk with Fingerbanged Wheat Germ Rippers Crying for Help in a Clotted Cream Gravy');
INSERT INTO menu VALUES(257,'The Schneider','French Canadian Crunch-Tweaked Beef Burger with Broasted Wheat Germ Portions Ripping a Bass Solo in a Bongwater Coulis');
INSERT INTO menu VALUES(258,'Jingle All the Way','42 Fluid Ounces of Lipid-Murdered Lamb Burger with Mentholated Jackfruit Jobbers Waterboarded in an Arizona Iced Tea Bearnaise');
INSERT INTO menu VALUES(259,'Lemonparty','42 Fluid Ounces of Cheddar-Drilled Pancetta Loaf with Galvanized Walnut Units Crying for Help in a Mr. Pibb Sauce');
INSERT INTO menu VALUES(260,'All the Pretty Horses','Laser Julienned Cool Ranch-Inserted Octopus Loaf with Mentholated Cauliflower Jobbers Partially Submerged in a GoGurt Reduction');
INSERT INTO menu VALUES(261,'Jingle All the Way','Spicy Italian Chipotle-Groped Corgi Burger with Pan Seared Snow Pea Portions Partially Submerged in a GoGurt Hollandaise');
INSERT INTO menu VALUES(262,'Hong','Rock and Roll Panko-Hammered Lamb Slab with Broasted Butternut Squash Clumps Partying ''til Dawn in an Arizona Iced Tea Donkey Sauce');
INSERT INTO menu VALUES(263,'Some Gave All','Uncle Kracker''s Signature Lipid-Fisted Baby Seal Enchiladas with Fry-olated Asparagus Rippers Hangin'' Ten in a Capri Sun Safari Fruits Coulis');
INSERT INTO menu VALUES(264,'Benghazi!','Spicy Italian Pimento-Smattered Rattlesnake Hunk with Taste-tosterone Marinated Zucchini Clumps Waterboarded in a Spray Butter Gravy');
INSERT INTO menu VALUES(265,'We Need To Talk About Kevin','Olde Tyme Pimento-Groped Veal Burger with Pan Seared Zucchini Rippers Curdling in a White Zin Sauce');
INSERT INTO menu VALUES(266,'Tits L''Amour','Uncle Kracker''s Signature Havarti-Smattered Octopus Roast with Steamed Wheat Germ Rippers Curdling in a Spray Butter Reduction');
INSERT INTO menu VALUES(267,'The Karen Carpenter','Peak Season Havarti-Drilled Lamb Tips with Fire Bruised Cauliflower Portions Frothing in a Stroh''s Flavor Puddle');
INSERT INTO menu VALUES(268,'BeefTech','Olde Tyme Cool Ranch-Hammered Octopus Enchiladas with Steamed Wheat Germ Clumps Ripping a Bass Solo in a Stroh''s Holocaust');
INSERT INTO menu VALUES(269,'Just the Tip','Laser Julienned Chipotle-Murdered Baby Seal Enchiladas with Triple-Fried Wheat Germ Grapplers Slam Dunked in a Clotted Cream Bearnaise');
INSERT INTO menu VALUES(270,'40 oz to Freedom','Pittsburgh''s Finest Crunch-Hammered Bison Slab with Broasted Ravioli Flapjacks Frothing in a Zima Flavor Puddle');
INSERT INTO menu VALUES(271,'The Karen Carpenter','Spicy Italian Cheddar-Drilled Beef Shank with Powdered Butternut Squash Flapjacks Floating in a Horseradish Au Jus');
INSERT INTO menu VALUES(272,'All the Pretty Horses','42 Fluid Ounces of Onion-Blasted Lamb Tips with Croc-Stomped Jackfruit Rippers Partying ''til Dawn in a Zima Demi-glace');
INSERT INTO menu VALUES(273,'Jingle All the Way','Uncle Kracker''s Signature Gruyere-Fisted Veal Cutlets with Vaped Quinoa Rippers Ripping a Bass Solo in a Powerade Sauce');
INSERT INTO menu VALUES(274,'The Dealbreaker','Uncle Kracker''s Signature Crunch-Tweaked Eel Slab with Thrice-Baked Quinoa Nugs Ripping a Bass Solo in a White Zin Flavor Puddle');
INSERT INTO menu VALUES(275,'Some Gave All','Guypocalyptic Crunch-Smashed Black Rhino Shank with Fry-olated Quinoa Units Mingling in a Horseradish Bearnaise');
INSERT INTO menu VALUES(276,'Some Gave All','Uncle Kracker''s Signature Gluten-Smattered Beef Burger with Powdered Quinoa Flapjacks Ripping a Bass Solo in a Mountain Dew Code Red Demi-glace');
INSERT INTO menu VALUES(277,'Gleaming the Cube Steak','Spicy Italian Cheddar-Hammered Corgi Loaf with Taste-tosterone Marinated Quinoa Griplets Partially Submerged in a Tampico Aioli');
INSERT INTO menu VALUES(278,'Jingle All the Way','Peak Season Acai-Tweaked Pork Slab with Pan Seared Wheat Germ Portions Curdling in a Stroh''s Bouillabaisse');
INSERT INTO menu VALUES(279,'The Lou Diamond Phillips','Laser Julienned Garlic-Blasted Falafel Loaf with Fire Bruised Snow Pea Clumps Crucified in a Capri Sun Safari Fruits Aioli');
INSERT INTO menu VALUES(280,'Snakes on a Plate','Peak Season Lipid-Groped Pork Roast with Broasted Jackfruit Jobbers Crucified in a Powerade Jacuzzi');
INSERT INTO menu VALUES(281,'The Dealbreaker','Partytime Pecan-Blasted Baby Seal Patties with Taste-tosterone Marinated Sweet Potato Grapplers Crying for Help in a Bongwater Aioli');
INSERT INTO menu VALUES(282,'Shake That Bear','Laser Julienned Lipid-Mauled Rattlesnake Patties with Croc-Stomped Jackfruit Griplets Stroking Out in a Surge Bearnaise');
INSERT INTO menu VALUES(283,'Stop or My Mom Will Shart','Guypocalyptic Garlic-Tweaked Duckling Shank with Pan Seared Ravioli Clumps Ripping a Bass Solo in a Queso Au Jus');
INSERT INTO menu VALUES(284,'Just the Tip','Peak Season Cheddar-Tweaked Veal Loaf with Triple-Fried Broccoli Raab Clumps Waterboarded in a Queso Bouillabaisse');
INSERT INTO menu VALUES(285,'Jingle All the Way','Guypocalyptic Garlic-Groped Pancetta Hunk with Broasted Ravioli Units Ripping a Bass Solo in a Spray Butter Demi-glace');
INSERT INTO menu VALUES(286,'Gleaming the Cube Steak','Guypocalyptic Onion-Mauled Corgi Doggers with Vaped Cauliflower Units Crucified in a White Zin Demi-glace');
INSERT INTO menu VALUES(287,'The Treat Williams','Guy''s Own Panko-Blasted Beef Cutlets with Pan Seared Cauliflower Units Partially Submerged in a Capri Sun Safari Fruits Demi-glace');
INSERT INTO menu VALUES(288,'The Dealbreaker','Uncle Kracker''s Signature Gluten-Mauled Manatee Slab with Fry-olated Ravioli Units Drowning in a Spray Butter Donkey Sauce');
INSERT INTO menu VALUES(289,'BeefTech','French Canadian Gruyere-Mauled Duckling Slab with Fingerbanged Zucchini Portions Curdling in a Zima Coulis');
INSERT INTO menu VALUES(290,'My Giant','Guy''s Own Crunch-Drilled Lamb Cutlets with Taste-tosterone Marinated Ravioli Flapjacks Hangin'' Ten in a Sunny D Hollandaise');
INSERT INTO menu VALUES(291,'My Giant','Guypocalyptic Pecan-Fisted Veal Shank with Fry-olated Quinoa Grapplers Curdling in an Arizona Iced Tea Gravy');
INSERT INTO menu VALUES(292,'Don''t Tread on Meat','French Canadian Cheddar-Creamed Corgi Patties with Mentholated Asparagus Grapplers Curdling in a Bongwater Bouillabaisse');
INSERT INTO menu VALUES(293,'Gleaming the Cube Steak','Guypocalyptic Garlic-Anointed Bison Doggers with Mentholated Sweet Potato Tidbits Implemented in a Spray Butter Demi-glace');
INSERT INTO menu VALUES(294,'The Lou Diamond Phillips','Peak Season Gluten-Smashed Rattlesnake Hunk with Powdered Asparagus Griplets Fornicating in a Queso Aioli');
INSERT INTO menu VALUES(295,'We Need To Talk About Kevin','Rock and Roll Lipid-Groped Pork Roast with Fire Bruised Quinoa Grapplers Curdling in a Tampico Demi-glace');
INSERT INTO menu VALUES(296,'Dr. T and the Women','Spicy Italian Pimento-Groped Baby Seal Enchiladas with Fry-olated Ravioli Nugs Crying for Help in an Arizona Iced Tea Au Jus');
INSERT INTO menu VALUES(297,'My Giant','All-American Gruyere-Smattered Eel Flatbread with Thrice-Baked Edamame Tidbits Slam Dunked in a Zima Hollandaise');
INSERT INTO menu VALUES(298,'The Dealbreaker','Peak Season MSG-Smattered Corgi Tips with Croc-Stomped Zucchini Jammers Crucified in a Mr. Pibb Au Jus');
INSERT INTO menu VALUES(299,'Hong','Peak Season Pecan-Drilled Octopus Cutlets with Finger-Rolled Wheat Germ Clumps Crucified in a Tampico Holocaust');
INSERT INTO menu VALUES(300,'C. Thomas Howell IV','Jack Daniels Lipid-Blasted Bacon Burger with Vaped Cauliflower Griplets Ripping a Bass Solo in a GoGurt Gravy');
INSERT INTO menu VALUES(301,'The Karen Carpenter','Partytime Pimento-Tweaked Octopus Loaf with Triple-Fried Zucchini Portions Crucified in a Clotted Cream Jacuzzi');
INSERT INTO menu VALUES(302,'Lemonparty','Guy''s Own Pimento-Thrusted Octopus Doggers with Vaped Broccoli Raab Tidbits Coming of Age in a Tampico Demi-glace');
INSERT INTO menu VALUES(303,'Two Grills One Cup','Partytime Lipid-Smattered Bacon Bits with Taste-tosterone Marinated Jackfruit Units Implemented in a 5-Hour Energy Bearnaise');
INSERT INTO menu VALUES(304,'That''s What She Said','Partytime Cheddar-Groped Veal Cutlets with Triple-Fried Sweet Potato Griplets Partially Submerged in a Watermelon Four Loko Bouillabaisse');
INSERT INTO menu VALUES(305,'Two Grills One Cup','Pittsburgh''s Finest Crunch-Anointed Pancetta Doggers with Pan Seared Edamame Tidbits Drowning in a Powerade Coulis');
INSERT INTO menu VALUES(306,'Who Let the Dogs In?','Spicy Italian Crunch-Fisted Lamb Roast with Windswept Wheat Germ Nugs Stroking Out in a Tampico Flavor Puddle');
INSERT INTO menu VALUES(307,'The Treat Williams','Uncle Kracker''s Signature Pimento-Inserted Pork Patties with Thrice-Baked Zucchini Flapjacks Frothing in a Stroh''s Coulis');
INSERT INTO menu VALUES(308,'Jingle All the Way','Laser Julienned Pecan-Murdered Pancetta Burger with Windswept Walnut Griplets Mingling in a Surge Gravy');
INSERT INTO menu VALUES(309,'That''s What She Said','42 Fluid Ounces of Garlic-Hammered Duckling Roast with Windswept Cauliflower Grapplers Drowning in a Capri Sun Safari Fruits Sauce');
INSERT INTO menu VALUES(310,'Tijuana Flavorwave','Jack Daniels Cheddar-Fisted Veal Tips with Thrice-Baked Jackfruit Griplets Drowning in a Tampico Au Jus');
INSERT INTO menu VALUES(311,'What I Got','French Canadian Pimento-Smattered Black Rhino Slab with Croc-Stomped Edamame Flapjacks Stroking Out in a Mountain Dew Code Red Hollandaise');
INSERT INTO menu VALUES(312,'Guyway to Heaven','Peak Season Acai-Creamed Black Rhino Loaf with Vaped Walnut Portions Floating in a Zima Donkey Sauce');
INSERT INTO menu VALUES(313,'Tijuana Flavorwave','Spicy Italian Chipotle-Groped Beef Flatbread with Finger-Rolled Sweet Potato Flapjacks Crying for Help in a Tampico Aioli');
INSERT INTO menu VALUES(314,'The Eddie Money Shot','Hot Rods of Gluten-Tweaked Duckling Roast with Fry-olated Sweet Potato Tidbits Partially Submerged in a Stroh''s Flavor Puddle');
INSERT INTO menu VALUES(315,'Shake That Bear','Uncle Kracker''s Signature Acai-Fisted Manatee Hunk with Broasted Sweet Potato Griplets Marinated in a Watermelon Four Loko Jacuzzi');
INSERT INTO menu VALUES(316,'The Lou Diamond Phillips','Rock and Roll Cool Ranch-Blasted Lamb Loaf with Triple-Fried Broccoli Raab Units Twerking in a Clotted Cream Coulis');
INSERT INTO menu VALUES(317,'Drops of Jupiter','Laser Julienned Pimento-Inserted Duckling Loaf with Powdered Zucchini Jobbers Floating in a Clotted Cream Coulis');
INSERT INTO menu VALUES(318,'That''s What She Said','Guy''s Famous MSG-Smashed Bacon Loaf with Broasted Jackfruit Units Mingling in a Mountain Dew Code Red Flavor Puddle');
INSERT INTO menu VALUES(319,'Stop or My Mom Will Shart','Guy''s Own Cool Ranch-Groped Lamb Shank with Taste-tosterone Marinated Walnut Grapplers Slam Dunked in a Horseradish Bouillabaisse');
INSERT INTO menu VALUES(320,'Turn Down for What','Laser Julienned Pimento-Tweaked Corgi Patties with Galvanized Zucchini Griplets Fornicating in a Capri Sun Safari Fruits Coulis');
INSERT INTO menu VALUES(321,'The Vanderbilt','Rock and Roll Pimento-Creamed Bacon Doggers with Vaped Edamame Rippers Marinated in an Arizona Iced Tea Aioli');
INSERT INTO menu VALUES(322,'Guyway to Heaven','All-American Gruyere-Smattered Veal Loaf with Purse-Snatched Asparagus Grapplers Crying for Help in a Powerade Coulis');
INSERT INTO menu VALUES(323,'Three Men and a Little Gravy','Uncle Kracker''s Signature Cheddar-Fisted Duckling Burger with Finger-Rolled Quinoa Jobbers Crying for Help in a Queso Reduction');
INSERT INTO menu VALUES(324,'The Lou Diamond Phillips','Fancy Cut Chipotle-Smashed Corgi Patties with Windswept Edamame Nugs Partially Submerged in a Watermelon Four Loko Au Jus');
INSERT INTO menu VALUES(325,'Hong','Rock and Roll Gruyere-Inserted Pork Loaf with Purse-Snatched Wheat Germ Units Holding Their Own in a Queso Holocaust');
INSERT INTO menu VALUES(326,'The Dealbreaker','French Canadian Clam-Blasted Black Rhino Bits with Galvanized Sweet Potato Units Hangin'' Ten in a Clotted Cream Hollandaise');
INSERT INTO menu VALUES(327,'The Truth About Cats and Dogs','Peak Season Gruyere-Anointed Eel Bits with Galvanized Edamame Clumps Holding Their Own in a Watermelon Four Loko Sauce');
INSERT INTO menu VALUES(328,'Benghazi!','French Canadian Clam-Tweaked Manatee Loaf with Steamed Jackfruit Clumps Coming of Age in a 5-Hour Energy Hollandaise');
INSERT INTO menu VALUES(329,'The Lou Diamond Phillips','Rock and Roll Clam-Thrusted Black Rhino Doggers with Taste-tosterone Marinated Quinoa Portions Ripping a Bass Solo in a Powerade Demi-glace');
INSERT INTO menu VALUES(330,'Lady in Red','Peak Season Cheddar-Inserted Manatee Enchiladas with Finger-Rolled Broccoli Raab Jobbers Mingling in a Tampico Hearse');
INSERT INTO menu VALUES(331,'Lady in Red','Spicy Italian Chipotle-Blasted Bison Loaf with Croc-Stomped Zucchini Portions Partially Submerged in a 5-Hour Energy Hollandaise');
INSERT INTO menu VALUES(332,'Hong','Peak Season Gluten-Groped Bacon Slab with Thrice-Baked Butternut Squash Nugs Implemented in a Mr. Pibb Donkey Sauce');
INSERT INTO menu VALUES(333,'Turn Down for What','Guypocalyptic Havarti-Smattered Bacon Bits with Thrice-Baked Snow Pea Jobbers Crucified in a White Zin Reduction');
INSERT INTO menu VALUES(334,'The Schneider','Hot Rods of Gluten-Hammered Bacon Loaf with Thrice-Baked Ravioli Tidbits Partying ''til Dawn in a Surge Jacuzzi');
INSERT INTO menu VALUES(335,'The Schneider','Guy''s Famous Lipid-Hammered Pork Slab with Finger-Rolled Ravioli Portions Implemented in a Watermelon Four Loko Gravy');
INSERT INTO menu VALUES(336,'Your Funeral','Guypocalyptic Crunch-Thrusted Veal Doggers with Fire Bruised Walnut Flapjacks Crying for Help in a Bongwater Coulis');
INSERT INTO menu VALUES(337,'Tijuana Flavorwave','Olde Tyme Onion-Smashed Veal Burger with Finger-Rolled Quinoa Nugs Waterboarded in a Stroh''s Bouillabaisse');
INSERT INTO menu VALUES(338,'Lady in Red','Olde Tyme Onion-Drilled Pork Cutlets with Fry-olated Zucchini Nugs Holding Their Own in a Bongwater Reduction');
INSERT INTO menu VALUES(339,'Lady in Red','Laser Julienned Pecan-Murdered Octopus Patties with Galvanized Ravioli Jobbers Coming of Age in a Clotted Cream Hollandaise');
INSERT INTO menu VALUES(340,'Madea''s Family Reunion','All-American Clam-Groped Black Rhino Loaf with Taste-tosterone Marinated Butternut Squash Portions Ripping a Bass Solo in a Queso Gravy');
INSERT INTO menu VALUES(341,'Guyway to Heaven','French Canadian Crunch-Tweaked Black Rhino Burger with Purse-Snatched Edamame Portions Mingling in a Surge Reduction');
INSERT INTO menu VALUES(342,'Two Grills One Cup','French Canadian Gruyere-Smashed Veal Patties with Vaped Butternut Squash Griplets Crucified in a Powerade Jacuzzi');
INSERT INTO menu VALUES(343,'BeefTech','Spicy Italian MSG-Drilled Pork Enchiladas with Vaped Sweet Potato Jobbers Crucified in a White Zin Hollandaise');
INSERT INTO menu VALUES(344,'Stop or My Mom Will Shart','Peak Season Cool Ranch-Mauled Bison Patties with Fire Bruised Asparagus Flapjacks Ripping a Bass Solo in a White Zin Hollandaise');
INSERT INTO menu VALUES(345,'Lady in Red','Olde Tyme Panko-Creamed Manatee Cutlets with Powdered Snow Pea Portions Floating in a Bongwater Donkey Sauce');
INSERT INTO menu VALUES(346,'PT Cruised','Peak Season MSG-Anointed Black Rhino Cutlets with Fire Bruised Snow Pea Flapjacks Ripping a Bass Solo in a Capri Sun Safari Fruits Sauce');
INSERT INTO menu VALUES(347,'Stop or My Mom Will Shart','Guy''s Famous Garlic-Hammered Octopus Loaf with Pan Seared Walnut Griplets Slam Dunked in a Surge Reduction');
INSERT INTO menu VALUES(348,'40 oz to Freedom','Fancy Cut Gluten-Hammered Rattlesnake Shank with Steamed Walnut Jobbers Waterboarded in a GoGurt Hearse');
INSERT INTO menu VALUES(349,'BeefTech','Fancy Cut Lipid-Smattered Bacon Loaf with Windswept Edamame Jobbers Drowning in an Arizona Iced Tea Hearse');
INSERT INTO menu VALUES(350,'Stop or My Mom Will Shart','Uncle Kracker''s Signature Pimento-Thrashed Lamb Bits with Fingerbanged Ravioli Griplets Marinated in a Watermelon Four Loko Hollandaise');
INSERT INTO menu VALUES(351,'Tijuana Flavorwave','Partytime Acai-Thrusted Rattlesnake Shank with Triple-Fried Zucchini Clumps Curdling in a Sunny D Donkey Sauce');
INSERT INTO menu VALUES(352,'The Bringer of Pain to Your Face','Guy''s Famous Acai-Smattered Bacon Slab with Steamed Wheat Germ Clumps Mingling in a Tampico Gravy');
INSERT INTO menu VALUES(353,'C. Thomas Howell IV','Spicy Italian Garlic-Fisted Pancetta Bits with Finger-Rolled Asparagus Portions Twerking in a Clotted Cream Gravy');
INSERT INTO menu VALUES(354,'Hong','Hot Rods of Clam-Mauled Black Rhino Flatbread with Thrice-Baked Wheat Germ Jobbers Floating in a 5-Hour Energy Reduction');
INSERT INTO menu VALUES(355,'C. Thomas Howell IV','Hot Rods of Clam-Tweaked Rattlesnake Loaf with Triple-Fried Snow Pea Tidbits Crying for Help in a Tampico Jacuzzi');
INSERT INTO menu VALUES(356,'Some Gave All','Uncle Kracker''s Signature Havarti-Groped Falafel Loaf with Mentholated Butternut Squash Griplets Floating in an Arizona Iced Tea Reduction');
INSERT INTO menu VALUES(357,'Guyway to Heaven','Spicy Italian Clam-Smattered Falafel Loaf with Pan Seared Broccoli Raab Flapjacks Partying ''til Dawn in a Tampico Demi-glace');
INSERT INTO menu VALUES(358,'Who Let the Dogs In?','Laser Julienned Cool Ranch-Groped Corgi Shank with Fire Bruised Sweet Potato Portions Holding Their Own in a Surge Bearnaise');
INSERT INTO menu VALUES(359,'PT Cruised','Uncle Kracker''s Signature Panko-Anointed Baby Seal Hunk with Powdered Jackfruit Griplets Mingling in a Zima Hearse');
INSERT INTO menu VALUES(360,'Turn Down for What','Partytime Gruyere-Hammered Eel Cutlets with Powdered Sweet Potato Units Fornicating in a Mr. Pibb Demi-glace');
INSERT INTO menu VALUES(361,'The Truth About Cats and Dogs','Olde Tyme Gruyere-Mauled Pancetta Slab with Pan Seared Sweet Potato Nugs Crucified in a 5-Hour Energy Sauce');
INSERT INTO menu VALUES(362,'BeefTech','Jack Daniels Pecan-Blasted Veal Bits with Triple-Fried Sweet Potato Flapjacks Slam Dunked in a Horseradish Bouillabaisse');
INSERT INTO menu VALUES(363,'Benghazi!','Peak Season MSG-Drilled Beef Roast with Broasted Cauliflower Rippers Curdling in a Powerade Demi-glace');
INSERT INTO menu VALUES(364,'All the Pretty Horses','Olde Tyme Gruyere-Groped Duckling Burger with Fingerbanged Snow Pea Units Crucified in a Clarified Lard Aioli');
INSERT INTO menu VALUES(365,'Gleaming the Cube Steak','Guy''s Own Cool Ranch-Mauled Lamb Hunk with Powdered Sweet Potato Flapjacks Fornicating in a Zima Flavor Puddle');
INSERT INTO menu VALUES(366,'Your Funeral','Olde Tyme Gluten-Tweaked Bacon Roast with Thrice-Baked Quinoa Rippers Stroking Out in a Queso Gravy');
INSERT INTO menu VALUES(367,'The Bringer of Pain to Your Face','Rock and Roll Pimento-Inserted Rattlesnake Tips with Finger-Rolled Ravioli Clumps Curdling in a Powerade Hollandaise');
INSERT INTO menu VALUES(368,'Some Gave All','Fancy Cut Havarti-Drilled Pancetta Bits with Pan Seared Zucchini Jammers Crucified in a GoGurt Bouillabaisse');
INSERT INTO menu VALUES(369,'The Ghost Dad','Rock and Roll Havarti-Groped Veal Flatbread with Fry-olated Zucchini Jobbers Hangin'' Ten in a White Zin Coulis');
INSERT INTO menu VALUES(370,'The Lou Diamond Phillips','Olde Tyme Chipotle-Drilled Rattlesnake Hunk with Pan Seared Butternut Squash Jammers Hangin'' Ten in a 5-Hour Energy Coulis');
INSERT INTO menu VALUES(371,'How Do You Talk to an Angel?','Pittsburgh''s Finest Havarti-Mauled Duckling Tips with Thrice-Baked Wheat Germ Griplets Implemented in a Bongwater Holocaust');
INSERT INTO menu VALUES(372,'Juggaloaf','French Canadian Havarti-Murdered Rattlesnake Enchiladas with Steamed Butternut Squash Clumps Floating in a Clarified Lard Flavor Puddle');
INSERT INTO menu VALUES(373,'Your Funeral','All-American Onion-Murdered Beef Flatbread with Broasted Walnut Rippers Crying for Help in a Bongwater Reduction');
INSERT INTO menu VALUES(374,'Tijuana Flavorwave','Peak Season Pecan-Creamed Black Rhino Flatbread with Mentholated Sweet Potato Rippers Sevendusted in a Zima Bouillabaisse');
INSERT INTO menu VALUES(375,'Your Funeral','French Canadian Lipid-Inserted Manatee Loaf with Croc-Stomped Butternut Squash Grapplers Mingling in a Zima Jacuzzi');
INSERT INTO menu VALUES(376,'The Vanderbilt','Guy''s Famous Crunch-Fisted Lamb Hunk with Fire Bruised Quinoa Tidbits Crying for Help in a Mr. Pibb Holocaust');
INSERT INTO menu VALUES(377,'Your Funeral','Guy''s Famous Clam-Smashed Duckling Cutlets with Powdered Zucchini Jammers Coming of Age in an Arizona Iced Tea Reduction');
INSERT INTO menu VALUES(378,'All the Pretty Horses','Guypocalyptic Clam-Hammered Rattlesnake Loaf with Galvanized Jackfruit Tidbits Hangin'' Ten in an Arizona Iced Tea Holocaust');
INSERT INTO menu VALUES(379,'The Eddie Money Shot','Guypocalyptic MSG-Creamed Bacon Loaf with Fire Bruised Quinoa Rippers Crucified in a White Zin Gravy');
INSERT INTO menu VALUES(380,'The Eddie Money Shot','French Canadian Garlic-Thrashed Corgi Tips with Fingerbanged Wheat Germ Rippers Drowning in a Capri Sun Safari Fruits Aioli');
INSERT INTO menu VALUES(381,'My Giant','Peak Season Garlic-Smashed Pork Roast with Purse-Snatched Snow Pea Clumps Curdling in a 5-Hour Energy Aioli');
INSERT INTO menu VALUES(382,'Jingle All the Way','Hot Rods of Garlic-Smashed Veal Burger with Steamed Butternut Squash Griplets Sevendusted in a Mountain Dew Code Red Demi-glace');
INSERT INTO menu VALUES(383,'The Truth About Cats and Dogs','Olde Tyme Cool Ranch-Thrusted Manatee Doggers with Mentholated Ravioli Units Coming of Age in a Stroh''s Demi-glace');
INSERT INTO menu VALUES(384,'We Need To Talk About Kevin','Peak Season Chipotle-Drilled Manatee Shank with Powdered Broccoli Raab Griplets Crying for Help in a Zima Holocaust');
INSERT INTO menu VALUES(385,'The Frosting of the Tips','Guypocalyptic Cool Ranch-Mauled Bacon Shank with Pan Seared Ravioli Portions Hangin'' Ten in a Clarified Lard Holocaust');
INSERT INTO menu VALUES(386,'Stop or My Mom Will Shart','All-American Chipotle-Inserted Veal Loaf with Fry-olated Broccoli Raab Jammers Mingling in a Spray Butter Holocaust');
INSERT INTO menu VALUES(387,'All the Pretty Horses','Rock and Roll Lipid-Thrashed Eel Flatbread with Broasted Butternut Squash Nugs Hangin'' Ten in a Spray Butter Flavor Puddle');
INSERT INTO menu VALUES(388,'Shake That Bear','Peak Season Cheddar-Creamed Rattlesnake Bits with Mentholated Sweet Potato Grapplers Ripping a Bass Solo in a Clotted Cream Hearse');
INSERT INTO menu VALUES(389,'Don''t Tread on Meat','42 Fluid Ounces of Clam-Thrusted Lamb Patties with Galvanized Snow Pea Clumps Stroking Out in an Arizona Iced Tea Aioli');
INSERT INTO menu VALUES(390,'Drops of Jupiter','Pittsburgh''s Finest Cool Ranch-Creamed Pork Shank with Steamed Jackfruit Tidbits Sevendusted in a Powerade Sauce');
INSERT INTO menu VALUES(391,'Benghazi!','All-American Garlic-Thrusted Bison Burger with Powdered Sweet Potato Rippers Holding Their Own in a Capri Sun Safari Fruits Sauce');
INSERT INTO menu VALUES(392,'Madea''s Family Reunion','Guy''s Own Havarti-Hammered Duckling Roast with Triple-Fried Sweet Potato Units Waterboarded in a Mountain Dew Code Red Donkey Sauce');
INSERT INTO menu VALUES(393,'Lady in Red','42 Fluid Ounces of MSG-Smashed Falafel Flatbread with Broasted Broccoli Raab Jammers Mingling in a Mountain Dew Code Red Au Jus');
INSERT INTO menu VALUES(394,'The Vanderbilt','French Canadian MSG-Thrusted Rattlesnake Loaf with Broasted Asparagus Units Partially Submerged in a Spray Butter Aioli');
INSERT INTO menu VALUES(395,'Your Funeral','Guy''s Own Pecan-Drilled Eel Doggers with Mentholated Walnut Rippers Partially Submerged in a White Zin Holocaust');
INSERT INTO menu VALUES(396,'Turn Down for What','Rock and Roll Cheddar-Groped Pancetta Flatbread with Mentholated Butternut Squash Portions Stroking Out in a 5-Hour Energy Hearse');
INSERT INTO menu VALUES(397,'The Vanderbilt','All-American Crunch-Blasted Black Rhino Doggers with Powdered Quinoa Grapplers Stroking Out in a Clotted Cream Demi-glace');
INSERT INTO menu VALUES(398,'Benghazi!','Rock and Roll Pimento-Mauled Duckling Hunk with Croc-Stomped Snow Pea Flapjacks Mingling in a Tampico Bearnaise');
INSERT INTO menu VALUES(399,'Dr. T and the Women','French Canadian Chipotle-Smattered Pancetta Burger with Broasted Sweet Potato Nugs Curdling in a Clotted Cream Gravy');
INSERT INTO menu VALUES(400,'Two Grills One Cup','French Canadian MSG-Smashed Black Rhino Patties with Triple-Fried Zucchini Flapjacks Ripping a Bass Solo in a Bongwater Holocaust');
INSERT INTO menu VALUES(401,'PT Cruised','Jack Daniels Acai-Anointed Pork Slab with Taste-tosterone Marinated Quinoa Portions Implemented in a Tampico Jacuzzi');
INSERT INTO menu VALUES(402,'Some Gave All','Jack Daniels Lipid-Thrusted Baby Seal Flatbread with Purse-Snatched Zucchini Flapjacks Partially Submerged in a White Zin Hollandaise');
INSERT INTO menu VALUES(403,'The Karen Carpenter','Fancy Cut Pecan-Smattered Veal Loaf with Purse-Snatched Broccoli Raab Jammers Slam Dunked in a Mr. Pibb Coulis');
INSERT INTO menu VALUES(404,'Juggaloaf','Partytime Gluten-Blasted Pork Slab with Windswept Asparagus Portions Ripping a Bass Solo in a Watermelon Four Loko Jacuzzi');
INSERT INTO menu VALUES(405,'Lemonparty','Fancy Cut MSG-Thrusted Beef Hunk with Galvanized Jackfruit Portions Drowning in a Queso Jacuzzi');
INSERT INTO menu VALUES(406,'Who Let the Dogs In?','Olde Tyme Gluten-Groped Black Rhino Enchiladas with Vaped Sweet Potato Jobbers Curdling in a Horseradish Bouillabaisse');
INSERT INTO menu VALUES(407,'How Do You Talk to an Angel?','Guypocalyptic Clam-Smashed Beef Hunk with Broasted Broccoli Raab Units Frothing in a Zima Aioli');
INSERT INTO menu VALUES(408,'Don''t Tread on Meat','All-American Havarti-Anointed Black Rhino Burger with Pan Seared Walnut Grapplers Crucified in a Capri Sun Safari Fruits Reduction');
INSERT INTO menu VALUES(409,'BeefTech','All-American Panko-Mauled Baby Seal Loaf with Purse-Snatched Ravioli Portions Stroking Out in a Powerade Reduction');
INSERT INTO menu VALUES(410,'Some Gave All','Uncle Kracker''s Signature Crunch-Mauled Beef Enchiladas with Windswept Sweet Potato Flapjacks Implemented in an Arizona Iced Tea Bearnaise');
INSERT INTO menu VALUES(411,'The Bringer of Pain to Your Face','Guy''s Own Garlic-Blasted Pancetta Enchiladas with Powdered Cauliflower Flapjacks Mingling in a Spray Butter Reduction');
INSERT INTO menu VALUES(412,'C. Thomas Howell IV','Uncle Kracker''s Signature Crunch-Murdered Black Rhino Bits with Broasted Butternut Squash Flapjacks Crucified in a Watermelon Four Loko Hollandaise');
INSERT INTO menu VALUES(413,'40 oz to Freedom','Jack Daniels Chipotle-Hammered Bison Enchiladas with Fingerbanged Asparagus Tidbits Ripping a Bass Solo in a Watermelon Four Loko Reduction');
INSERT INTO menu VALUES(414,'The Eddie Money Shot','Fancy Cut Onion-Smattered Eel Loaf with Steamed Sweet Potato Flapjacks Partying ''til Dawn in a Horseradish Reduction');
INSERT INTO menu VALUES(415,'The Ghost Dad','Peak Season Pimento-Thrusted Lamb Loaf with Galvanized Jackfruit Grapplers Sevendusted in a Spray Butter Coulis');
INSERT INTO menu VALUES(416,'The Lou Diamond Phillips','Fancy Cut Cheddar-Hammered Duckling Bits with Taste-tosterone Marinated Broccoli Raab Portions Waterboarded in a Mr. Pibb Reduction');
INSERT INTO menu VALUES(417,'40 oz to Freedom','Jack Daniels Havarti-Smattered Corgi Loaf with Croc-Stomped Snow Pea Jammers Marinated in a Powerade Hearse');
INSERT INTO menu VALUES(418,'My Giant','Guy''s Famous Clam-Murdered Baby Seal Roast with Pan Seared Butternut Squash Jammers Ripping a Bass Solo in a Watermelon Four Loko Donkey Sauce');
INSERT INTO menu VALUES(419,'Juggaloaf','Spicy Italian Onion-Drilled Duckling Shank with Taste-tosterone Marinated Broccoli Raab Jammers Frothing in a Stroh''s Aioli');
INSERT INTO menu VALUES(420,'Drops of Jupiter','Guy''s Own Pimento-Fisted Beef Shank with Thrice-Baked Jackfruit Jammers Implemented in a Stroh''s Gravy');
INSERT INTO menu VALUES(421,'The Frosting of the Tips','Peak Season Lipid-Blasted Octopus Burger with Triple-Fried Butternut Squash Clumps Crying for Help in a Powerade Hollandaise');
INSERT INTO menu VALUES(422,'Three Men and a Little Gravy','Spicy Italian Panko-Creamed Beef Roast with Mentholated Snow Pea Clumps Floating in a Watermelon Four Loko Hollandaise');
INSERT INTO menu VALUES(423,'BeefTech','42 Fluid Ounces of Acai-Creamed Lamb Flatbread with Steamed Edamame Tidbits Implemented in a Powerade Bouillabaisse');
INSERT INTO menu VALUES(424,'C. Thomas Howell IV','All-American Acai-Mauled Octopus Flatbread with Broasted Zucchini Units Curdling in a Zima Hearse');
INSERT INTO menu VALUES(425,'The Treat Williams','Jack Daniels Gruyere-Creamed Black Rhino Roast with Fingerbanged Cauliflower Nugs Partying ''til Dawn in a Sunny D Hollandaise');
INSERT INTO menu VALUES(426,'The Treat Williams','Rock and Roll Gruyere-Blasted Duckling Cutlets with Fingerbanged Asparagus Rippers Partially Submerged in a Tampico Bearnaise');
INSERT INTO menu VALUES(427,'Who Let the Dogs In?','Uncle Kracker''s Signature Clam-Drilled Veal Hunk with Windswept Snow Pea Nugs Sevendusted in a Tampico Gravy');
INSERT INTO menu VALUES(428,'The Karen Carpenter','All-American Pimento-Mauled Pork Loaf with Mentholated Ravioli Jammers Stroking Out in a Queso Bouillabaisse');
INSERT INTO menu VALUES(429,'That''s What She Said','Laser Julienned Acai-Creamed Lamb Doggers with Broasted Cauliflower Clumps Hangin'' Ten in a Clotted Cream Flavor Puddle');
INSERT INTO menu VALUES(430,'Drops of Jupiter','Jack Daniels Gruyere-Fisted Baby Seal Bits with Croc-Stomped Zucchini Nugs Implemented in a Tampico Flavor Puddle');
INSERT INTO menu VALUES(431,'Three Men and a Little Gravy','Partytime Onion-Thrusted Bison Patties with Fingerbanged Ravioli Rippers Drowning in a Clotted Cream Reduction');
INSERT INTO menu VALUES(432,'The Eddie Money Shot','Guy''s Own Clam-Mauled Pancetta Tips with Broasted Jackfruit Rippers Twerking in a White Zin Hollandaise');
INSERT INTO menu VALUES(433,'Tits L''Amour','All-American MSG-Inserted Beef Cutlets with Finger-Rolled Quinoa Nugs Frothing in a Mr. Pibb Gravy');
INSERT INTO menu VALUES(434,'How Do You Talk to an Angel?','Spicy Italian Chipotle-Smattered Pork Cutlets with Purse-Snatched Walnut Flapjacks Floating in a Mountain Dew Code Red Hollandaise');
INSERT INTO menu VALUES(435,'Who Let the Dogs In?','Guy''s Own Pimento-Tweaked Beef Shank with Fry-olated Quinoa Rippers Mingling in a Queso Holocaust');
INSERT INTO menu VALUES(436,'The Karen Carpenter','Guy''s Own Clam-Tweaked Manatee Slab with Powdered Quinoa Jobbers Mingling in a Tampico Hearse');
INSERT INTO menu VALUES(437,'Shake That Bear','Olde Tyme Havarti-Tweaked Corgi Enchiladas with Triple-Fried Asparagus Portions Coming of Age in a Mr. Pibb Flavor Puddle');
INSERT INTO menu VALUES(438,'Shake That Bear','42 Fluid Ounces of Clam-Anointed Black Rhino Loaf with Triple-Fried Asparagus Clumps Fornicating in a Capri Sun Safari Fruits Flavor Puddle');
INSERT INTO menu VALUES(439,'Lady in Red','Olde Tyme Cheddar-Murdered Lamb Burger with Vaped Edamame Flapjacks Stroking Out in a Queso Bouillabaisse');
INSERT INTO menu VALUES(440,'We Need To Talk About Kevin','French Canadian Panko-Inserted Duckling Shank with Finger-Rolled Broccoli Raab Tidbits Curdling in a Mountain Dew Code Red Flavor Puddle');
INSERT INTO menu VALUES(441,'Benghazi!','All-American Pimento-Tweaked Rattlesnake Slab with Steamed Butternut Squash Griplets Implemented in a Watermelon Four Loko Hearse');
INSERT INTO menu VALUES(442,'C. Thomas Howell IV','Rock and Roll Panko-Thrusted Octopus Flatbread with Broasted Cauliflower Jammers Frothing in an Arizona Iced Tea Hollandaise');
INSERT INTO menu VALUES(443,'Madea''s Family Reunion','Guy''s Famous Chipotle-Thrashed Bacon Doggers with Pan Seared Quinoa Nugs Slam Dunked in a Queso Aioli');
INSERT INTO menu VALUES(444,'Madea''s Family Reunion','Fancy Cut Cheddar-Mauled Pancetta Tips with Triple-Fried Quinoa Grapplers Slam Dunked in a Mr. Pibb Demi-glace');
INSERT INTO menu VALUES(445,'The Treat Williams','Fancy Cut Pimento-Smashed Veal Slab with Thrice-Baked Butternut Squash Tidbits Waterboarded in a Queso Bouillabaisse');
INSERT INTO menu VALUES(446,'Jingle All the Way','Laser Julienned MSG-Mauled Eel Slab with Fingerbanged Broccoli Raab Jobbers Partying ''til Dawn in a Zima Reduction');
INSERT INTO menu VALUES(447,'Just the Tip','Peak Season Garlic-Inserted Bacon Doggers with Thrice-Baked Asparagus Nugs Hangin'' Ten in a White Zin Hollandaise');
INSERT INTO menu VALUES(448,'The Bringer of Pain to Your Face','Pittsburgh''s Finest Gruyere-Thrusted Duckling Hunk with Broasted Sweet Potato Clumps Implemented in a Stroh''s Bouillabaisse');
INSERT INTO menu VALUES(449,'All the Pretty Horses','Pittsburgh''s Finest Pecan-Smashed Black Rhino Slab with Pan Seared Wheat Germ Units Floating in an Arizona Iced Tea Gravy');
INSERT INTO menu VALUES(450,'The Truth About Cats and Dogs','Guypocalyptic Acai-Smashed Corgi Slab with Thrice-Baked Zucchini Grapplers Fornicating in a Zima Demi-glace');
INSERT INTO menu VALUES(451,'PT Cruised','Hot Rods of Panko-Fisted Falafel Patties with Steamed Cauliflower Flapjacks Floating in a Queso Hearse');
INSERT INTO menu VALUES(452,'The Lou Diamond Phillips','Rock and Roll Gruyere-Fisted Veal Roast with Vaped Ravioli Jobbers Ripping a Bass Solo in a GoGurt Aioli');
INSERT INTO menu VALUES(453,'Your Funeral','French Canadian Cool Ranch-Smashed Veal Tips with Broasted Sweet Potato Jobbers Holding Their Own in a Horseradish Coulis');
INSERT INTO menu VALUES(454,'The Karen Carpenter','Fancy Cut Acai-Drilled Manatee Patties with Croc-Stomped Broccoli Raab Rippers Stroking Out in a Mr. Pibb Demi-glace');
INSERT INTO menu VALUES(455,'40 oz to Freedom','All-American Pecan-Thrashed Pork Tips with Thrice-Baked Ravioli Units Hangin'' Ten in a Tampico Jacuzzi');
INSERT INTO menu VALUES(456,'We Need To Talk About Kevin','Pittsburgh''s Finest Cool Ranch-Mauled Manatee Roast with Steamed Edamame Grapplers Frothing in a Sunny D Donkey Sauce');
INSERT INTO menu VALUES(457,'Drops of Jupiter','All-American Lipid-Inserted Veal Burger with Powdered Snow Pea Jobbers Frothing in a Mr. Pibb Coulis');
INSERT INTO menu VALUES(458,'All the Pretty Horses','Rock and Roll Gruyere-Groped Veal Enchiladas with Pan Seared Quinoa Units Twerking in an Arizona Iced Tea Jacuzzi');
INSERT INTO menu VALUES(459,'All the Pretty Horses','Uncle Kracker''s Signature Chipotle-Drilled Duckling Hunk with Fry-olated Asparagus Flapjacks Crying for Help in a Queso Flavor Puddle');
INSERT INTO menu VALUES(460,'The Vanderbilt','Rock and Roll Panko-Murdered Beef Enchiladas with Fingerbanged Walnut Jammers Holding Their Own in a Surge Holocaust');
INSERT INTO menu VALUES(461,'Snakes on a Plate','Rock and Roll Gluten-Groped Falafel Cutlets with Pan Seared Cauliflower Jobbers Crucified in a Tampico Aioli');
INSERT INTO menu VALUES(462,'The Schneider','42 Fluid Ounces of Pimento-Drilled Bacon Burger with Windswept Walnut Flapjacks Stroking Out in a Stroh''s Hollandaise');
INSERT INTO menu VALUES(463,'Three Men and a Little Gravy','Guypocalyptic Gruyere-Hammered Pork Doggers with Pan Seared Wheat Germ Rippers Waterboarded in a Stroh''s Bouillabaisse');
INSERT INTO menu VALUES(464,'Tits L''Amour','Uncle Kracker''s Signature Garlic-Creamed Beef Loaf with Fire Bruised Wheat Germ Griplets Waterboarded in a Queso Jacuzzi');
INSERT INTO menu VALUES(465,'That''s What She Said','Spicy Italian Pecan-Smashed Rattlesnake Bits with Triple-Fried Broccoli Raab Units Implemented in a Tampico Donkey Sauce');
INSERT INTO menu VALUES(466,'The Dealbreaker','Jack Daniels Panko-Creamed Pork Cutlets with Windswept Ravioli Units Frothing in a Watermelon Four Loko Flavor Puddle');
INSERT INTO menu VALUES(467,'How Do You Talk to an Angel?','Rock and Roll MSG-Anointed Corgi Cutlets with Thrice-Baked Walnut Clumps Stroking Out in a Surge Bouillabaisse');
INSERT INTO menu VALUES(468,'Tijuana Flavorwave','French Canadian Chipotle-Hammered Beef Slab with Mentholated Quinoa Jammers Slam Dunked in a Surge Aioli');
INSERT INTO menu VALUES(469,'40 oz to Freedom','Olde Tyme Gruyere-Inserted Falafel Loaf with Mentholated Wheat Germ Portions Ripping a Bass Solo in a 5-Hour Energy Sauce');
INSERT INTO menu VALUES(470,'Lady in Red','Hot Rods of Onion-Anointed Pancetta Bits with Fry-olated Snow Pea Clumps Ripping a Bass Solo in a Bongwater Demi-glace');
INSERT INTO menu VALUES(471,'Jingle All the Way','Hot Rods of Onion-Fisted Octopus Bits with Fire Bruised Asparagus Nugs Crying for Help in a Surge Au Jus');
INSERT INTO menu VALUES(472,'Guyway to Heaven','Laser Julienned Cheddar-Thrusted Pork Slab with Taste-tosterone Marinated Asparagus Griplets Coming of Age in a GoGurt Holocaust');
INSERT INTO menu VALUES(473,'Some Gave All','Olde Tyme Gruyere-Inserted Lamb Roast with Windswept Asparagus Portions Fornicating in a Watermelon Four Loko Holocaust');
INSERT INTO menu VALUES(474,'That''s What She Said','Uncle Kracker''s Signature MSG-Inserted Lamb Loaf with Mentholated Wheat Germ Portions Waterboarded in a Sunny D Aioli');
INSERT INTO menu VALUES(475,'PT Cruised','Peak Season Panko-Inserted Pancetta Loaf with Thrice-Baked Wheat Germ Grapplers Mingling in a GoGurt Jacuzzi');
INSERT INTO menu VALUES(476,'C. Thomas Howell IV','Guy''s Famous Panko-Fisted Pancetta Enchiladas with Galvanized Snow Pea Nugs Sevendusted in a White Zin Flavor Puddle');
INSERT INTO menu VALUES(477,'Jingle All the Way','Guypocalyptic Garlic-Blasted Baby Seal Burger with Powdered Snow Pea Clumps Marinated in a Zima Hollandaise');
INSERT INTO menu VALUES(478,'All the Pretty Horses','Rock and Roll Gruyere-Hammered Duckling Flatbread with Windswept Snow Pea Flapjacks Twerking in a Horseradish Coulis');
INSERT INTO menu VALUES(479,'The Truth About Cats and Dogs','Uncle Kracker''s Signature Cool Ranch-Smashed Manatee Loaf with Taste-tosterone Marinated Zucchini Portions Hangin'' Ten in a White Zin Donkey Sauce');
INSERT INTO menu VALUES(480,'C. Thomas Howell IV','Partytime Gruyere-Thrashed Eel Cutlets with Powdered Broccoli Raab Nugs Hangin'' Ten in a Queso Flavor Puddle');
INSERT INTO menu VALUES(481,'The Vanderbilt','Pittsburgh''s Finest Panko-Tweaked Octopus Burger with Croc-Stomped Zucchini Units Frothing in a Mr. Pibb Hearse');
INSERT INTO menu VALUES(482,'Don''t Tread on Meat','Spicy Italian Pecan-Anointed Pancetta Tips with Fire Bruised Ravioli Jammers Holding Their Own in a Surge Hollandaise');
INSERT INTO menu VALUES(483,'The Dealbreaker','French Canadian Chipotle-Murdered Eel Cutlets with Fingerbanged Asparagus Flapjacks Holding Their Own in an Arizona Iced Tea Au Jus');
INSERT INTO menu VALUES(484,'Some Gave All','Fancy Cut Pecan-Fisted Lamb Doggers with Fry-olated Ravioli Griplets Crucified in a Queso Sauce');
INSERT INTO menu VALUES(485,'Turn Down for What','Uncle Kracker''s Signature Onion-Murdered Eel Hunk with Triple-Fried Ravioli Jammers Crying for Help in a Spray Butter Bouillabaisse');
INSERT INTO menu VALUES(486,'Drops of Jupiter','French Canadian Panko-Thrashed Corgi Doggers with Galvanized Quinoa Portions Waterboarded in a Stroh''s Coulis');
INSERT INTO menu VALUES(487,'All the Pretty Horses','Fancy Cut Lipid-Thrusted Pancetta Doggers with Finger-Rolled Quinoa Griplets Curdling in a Queso Bearnaise');
INSERT INTO menu VALUES(488,'40 oz to Freedom','Guy''s Famous Gruyere-Thrusted Pancetta Slab with Broasted Zucchini Jobbers Coming of Age in a 5-Hour Energy Jacuzzi');
INSERT INTO menu VALUES(489,'Who Let the Dogs In?','42 Fluid Ounces of MSG-Creamed Black Rhino Roast with Mentholated Quinoa Portions Curdling in an Arizona Iced Tea Coulis');
INSERT INTO menu VALUES(490,'Don''t Tread on Meat','Rock and Roll Lipid-Creamed Baby Seal Loaf with Taste-tosterone Marinated Ravioli Flapjacks Partying ''til Dawn in a Zima Bearnaise');
INSERT INTO menu VALUES(491,'The Bringer of Pain to Your Face','Pittsburgh''s Finest Clam-Smattered Eel Enchiladas with Triple-Fried Asparagus Grapplers Marinated in a Tampico Donkey Sauce');
INSERT INTO menu VALUES(492,'The Frosting of the Tips','Guy''s Famous Pecan-Smashed Octopus Doggers with Fry-olated Cauliflower Jammers Drowning in a 5-Hour Energy Bearnaise');
INSERT INTO menu VALUES(493,'Juggaloaf','French Canadian Gruyere-Smattered Corgi Doggers with Fry-olated Asparagus Jammers Implemented in a Sunny D Gravy');
INSERT INTO menu VALUES(494,'Two Grills One Cup','All-American MSG-Thrusted Bison Bits with Fire Bruised Asparagus Jobbers Crucified in a Clarified Lard Coulis');
INSERT INTO menu VALUES(495,'Your Funeral','Pittsburgh''s Finest Pecan-Tweaked Duckling Loaf with Broasted Jackfruit Tidbits Frothing in a Queso Jacuzzi');
INSERT INTO menu VALUES(496,'Gleaming the Cube Steak','French Canadian Pimento-Creamed Falafel Hunk with Steamed Cauliflower Flapjacks Mingling in a Mr. Pibb Sauce');
INSERT INTO menu VALUES(497,'Lady in Red','Partytime MSG-Inserted Octopus Roast with Mentholated Snow Pea Jobbers Stroking Out in a White Zin Coulis');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('quotes',7);
INSERT INTO sqlite_sequence VALUES('menu',497);
COMMIT;
